Repository DataDog/browser-sdk, pull requests merged in 2023-12, with the labels that each got.

#2528 Update repository.datadog.yml
  repository.datadog.yml
Labels: team:rum-browser

#2527 🐛 [RUM-2280] fix duplicated mutations when using Shadow DOM
  packages/rum/src/domain/record/record.spec.ts
  packages/rum/src/domain/record/shadowRootsController.ts
Labels: staging-50

#2531 🔊[RUM-2324] Telemetry on other wrong LCP cases
  packages/core/src/tools/experimentalFeatures.ts
  packages/rum-core/src/browser/performanceCollection.ts
  packages/rum-core/src/domain/view/viewMetrics/trackLargestContentfulPaint.ts
Labels: staging-50, staging-51
