Repository DataDog/browser-sdk, pull requests merged in 2023-07, with the labels that each got.

#2319 ♻️ [RUM-232] create a `@datadog/browser-worker` package
  .eslintrc.js
  .github/codeql-config.yml
  .wokeignore
  eslint-local-rules/disallowSideEffects.js
  package.json
  packages/rum/package.json
  packages/rum/src/domain/segmentCollection/deflateWorker.js
  packages/rum/src/domain/segmentCollection/deflateWorker.spec.ts
  packages/rum/src/domain/segmentCollection/index.ts
  packages/rum/src/domain/segmentCollection/segment.ts
  packages/rum/src/domain/segmentCollection/segmentCollection.ts
  packages/rum/src/domain/segmentCollection/startDeflateWorker.spec.ts
  packages/rum/src/domain/segmentCollection/startDeflateWorker.ts
  packages/rum/test/mockWorker.ts
  packages/worker/.npmignore
  packages/worker/.yarnrc
  packages/worker/README.md
  packages/worker/package.json
  packages/worker/scripts/build-worker-string.js
  packages/worker/src/boot/startWorker.ts
  packages/worker/src/domain/deflate.d.ts
  packages/worker/src/domain/deflate.js
  packages/worker/src/entries/main.ts
  packages/worker/src/types.ts
  packages/worker/string/package.json
  packages/worker/tsconfig.json
  packages/worker/webpack.config.js
  test/app/package.json
  test/app/yarn.lock
  yarn.lock
Labels: staging-27

#2331 👷 [RUM-232] fix worker/string package
  packages/worker/.npmignore
  packages/worker/scripts/build-worker-string.js
  packages/worker/string/package.json
Labels: staging-28

#2335 🔉 monitor reported errors
  packages/logs/src/boot/startLogs.ts
  packages/rum-core/src/boot/startRum.ts
  packages/rum/src/boot/startRecording.ts
Labels: staging-28

#2341 🐛 Avoid setting non-object values for contexts
  packages/core/src/tools/serialisation/contextManager.spec.ts
  packages/core/src/tools/serialisation/contextManager.ts
Labels: staging-29

#2346 ♻️ [RUM-249] update worker protocol
  packages/core/src/domain/telemetry/telemetry.ts
  packages/core/src/tools/utils/byteUtils.spec.ts
  packages/core/src/tools/utils/byteUtils.ts
  packages/rum/src/domain/segmentCollection/segment.ts
  packages/rum/src/domain/segmentCollection/startDeflateWorker.spec.ts
  packages/rum/src/domain/segmentCollection/startDeflateWorker.ts
  packages/rum/test/mockWorker.ts
  packages/worker/package.json
  packages/worker/src/boot/startWorker.spec.ts
  packages/worker/src/boot/startWorker.ts
  packages/worker/src/domain/deflate.d.ts
  packages/worker/src/types.ts
  test/app/yarn.lock
  yarn.lock
Labels: staging-30

#2353 👷Use SDK version format supported by backend
  scripts/lib/build-env.js
Labels: staging-30
