Repository DataDog/browser-sdk, pull requests merged in 2023-06, with the labels that each got.

#2275 💥 [RUMF-1589] automatically start recording
  packages/rum-core/src/boot/rumPublicApi.spec.ts
  packages/rum-core/src/boot/rumPublicApi.ts
  packages/rum-core/src/domain/configuration.spec.ts
  packages/rum-core/src/domain/configuration.ts
  packages/rum/src/boot/recorderApi.spec.ts
  packages/rum/src/boot/recorderApi.ts
  test/e2e/lib/helpers/replay.ts
  test/e2e/scenario/recorder/recorder.scenario.ts
  test/e2e/scenario/recorder/shadowDom.scenario.ts
  test/e2e/scenario/recorder/viewports.scenario.ts
  test/e2e/scenario/rum/sessions.scenario.ts
Labels: staging-23

#2284 ♻️ [RUMF-1555] Remove deprecated context manager APIs
  packages/core/src/tools/serialisation/contextManager.spec.ts
  packages/core/src/tools/serialisation/contextManager.ts
  packages/logs/src/domain/logger.ts
  packages/rum-core/src/domain/startCustomerDataTelemetry.spec.ts
  packages/rum-core/src/domain/startCustomerDataTelemetry.ts
Labels: staging-23

#2286 💥 [RUMF-1555] Remove `event` in action domain context
  packages/rum-core/src/domain/rumEventsCollection/action/actionCollection.spec.ts
  packages/rum-core/src/domain/rumEventsCollection/action/actionCollection.ts
  packages/rum-core/src/domainContext.types.ts
  packages/rum/src/domain/record/observers/frustrationObserver.spec.ts
Labels: staging-23

#2285 💥 [RUMF-1555] Rework logger context APIs
  packages/logs/src/domain/logger.spec.ts
  packages/logs/src/domain/logger.ts
Labels: staging-23

#2292 👷 Update TypeScript to 5.1.3
  package.json
  packages/core/src/domain/report/browser.types.ts
  packages/core/src/domain/report/reportObservable.spec.ts
  packages/core/src/domain/report/reportObservable.ts
  packages/core/test/emulate/stubReportApis.ts
  yarn.lock
Labels: dependencies

#2298 💥[RUMF-1230] Only apply main logger configuration to its own logs
  packages/logs/src/boot/logsPublicApi.ts
  packages/logs/src/boot/startLogs.spec.ts
  packages/logs/src/boot/startLogs.ts
  packages/logs/src/domain/assembly.spec.ts
  packages/logs/src/domain/assembly.ts
  packages/logs/src/domain/lifeCycle.ts
  packages/logs/src/domain/logsCollection/logger/loggerCollection.spec.ts
  packages/logs/src/domain/logsCollection/logger/loggerCollection.ts
Labels: staging-25

#2303 💥 [RUMF-1556] Typings: consistent beforeSend return type
  packages/logs/src/domain/assembly.spec.ts
  packages/logs/src/domain/configuration.ts
  packages/rum-core/src/domain/assembly.spec.ts
  packages/rum-core/src/domain/configuration.ts
  test/e2e/scenario/logs.scenario.ts
  test/e2e/scenario/rum/init.scenario.ts
Labels: staging-25

#2300 💥 [RUMF-1557] beforeSend domain context: use PerformanceEntry
  packages/rum-core/src/browser/performanceCollection.spec.ts
  packages/rum-core/src/browser/performanceCollection.ts
  packages/rum-core/src/domain/rumEventsCollection/longTask/longTaskCollection.spec.ts
  packages/rum-core/src/domain/rumEventsCollection/longTask/longTaskCollection.ts
  packages/rum-core/src/domain/rumEventsCollection/resource/resourceCollection.ts
  packages/rum-core/src/domainContext.types.ts
  packages/rum-core/test/fixtures.ts
Labels: staging-25

#2313 🐛 [RUMF-1613] fix session replay performance regression
  packages/rum/src/domain/record/observers/inputObserver.spec.ts
  packages/rum/src/domain/record/observers/inputObserver.ts
  packages/rum/src/domain/record/shadowRootsController.ts
Labels: staging-26
