Repository DataDog/browser-sdk, pull requests merged in 2023-09, with the labels that each got.

#2405 🐛 fix INP support detection
  packages/rum-core/src/domain/rumEventsCollection/view/viewMetrics/trackInteractionToNextPaint.ts
Labels: staging-35

#2397 🐛 fix dynamic style serialization
  packages/rum/src/domain/record/privacy.ts
  packages/rum/src/domain/record/serialization/htmlAst.specHelper.ts
  packages/rum/src/domain/record/serialization/serializeAttributes.ts
  packages/rum/src/domain/record/serialization/serializeNode.spec.ts
  packages/rum/src/domain/record/serialization/serializeNode.ts
Labels: staging-35

#2428 ♻️ Use performance entry fixtures in tests
  packages/rum-core/src/boot/startRum.spec.ts
  packages/rum-core/src/browser/performanceCollection.ts
  packages/rum-core/src/domain/longTask/longTaskCollection.spec.ts
  packages/rum-core/src/domain/resource/matchRequestTiming.spec.ts
  packages/rum-core/src/domain/resource/resourceCollection.spec.ts
  packages/rum-core/src/domain/view/setupViewTest.specHelper.ts
  packages/rum-core/src/domain/view/trackViews.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/trackFirstContentfulPaint.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/trackInitialViewMetrics.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/trackLoadingTime.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/trackNavigationTimings.spec.ts
  packages/rum-core/src/domain/waitPageActivityEnd.spec.ts
  packages/rum-core/test/fixtures.ts
Labels: staging-37

#2432 ✨ [RUM-1062] add a prefix to all console message displayed by the SDK
  packages/core/src/tools/display.ts
  packages/rum/src/boot/startRecording.spec.ts
  packages/rum/src/domain/deflate/deflateWorker.spec.ts
  test/e2e/scenario/rum/init.scenario.ts
Labels: staging-38

#2436 🔇 Remove cwv attribution telemetry
  packages/rum-core/src/boot/rumPublicApi.ts
  packages/rum-core/src/boot/startRum.spec.ts
  packages/rum-core/src/boot/startRum.ts
  packages/rum-core/src/domain/view/setupViewTest.specHelper.ts
  packages/rum-core/src/domain/view/startWebVitalTelemetryDebug.ts
  packages/rum-core/src/domain/view/trackViews.ts
  packages/rum-core/src/domain/view/viewCollection.spec.ts
  packages/rum-core/src/domain/view/viewCollection.ts
  packages/rum-core/src/domain/view/viewMetrics/trackCommonViewMetrics.ts
  packages/rum-core/src/domain/view/viewMetrics/trackCumulativeLayoutShift.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/trackCumulativeLayoutShift.ts
  packages/rum-core/src/domain/view/viewMetrics/trackFirstInput.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/trackFirstInput.ts
  packages/rum-core/src/domain/view/viewMetrics/trackInitialViewMetrics.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/trackInitialViewMetrics.ts
  packages/rum-core/src/domain/view/viewMetrics/trackLargestContentfulPaint.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/trackLargestContentfulPaint.ts
  packages/rum-core/test/index.ts
  packages/rum-core/test/noopRecorderApi.ts
  packages/rum-core/test/noopWebVitalTelemetryDebug.ts
  packages/rum-slim/src/entries/main.ts
  packages/rum/src/boot/recorderApi.ts
  packages/rum/src/domain/record/index.ts
Labels: staging-39
