Repository DataDog/browser-sdk, pull requests merged in 2023-10, with the labels that each got.

#2449  🔊 Add INP telemetry
  packages/rum-core/src/browser/performanceCollection.ts
  packages/rum-core/src/domain/view/viewMetrics/trackInteractionToNextPaint.ts
Labels: staging-40

#2451 🐛 [RUM-1325] fix memory leak when using shadow dom
  packages/rum-core/src/browser/htmlDomUtils.spec.ts
  packages/rum-core/src/browser/htmlDomUtils.ts
  packages/rum/src/domain/record/observers/mutationObserver.spec.ts
  packages/rum/src/domain/record/observers/mutationObserver.ts
Labels: staging-40

#2466 🐛 [RUM-1360] Cap INP outliers
  packages/rum-core/src/domain/view/trackViews.ts
  packages/rum-core/src/domain/view/viewMetrics/trackCommonViewMetrics.ts
  packages/rum-core/src/domain/view/viewMetrics/trackInteractionToNextPaint.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/trackInteractionToNextPaint.ts
Labels: staging-42

#2486 🐛 [RUM-1863] fix iOS webview detection
  packages/core/src/tools/utils/browserDetection.spec.ts
  packages/core/src/tools/utils/browserDetection.ts
Labels: staging-44

#2416 ✅ [RUM-253] add E2E tests related to compression
  test/e2e/lib/framework/intakeRegistry.ts
  test/e2e/lib/framework/serverApps/intake.ts
  test/e2e/scenario/recorder/recorder.scenario.ts
  test/e2e/scenario/transport.scenario.ts
Labels: staging-36
