Repository DataDog/browser-sdk, pull requests merged in 2023-05, with the labels that each got.

#2197 🐛 Revert Errors serialization behavior
  packages/core/src/tools/serialisation/sanitize.spec.ts
  packages/core/src/tools/serialisation/sanitize.ts
Labels: staging-18

#2234 🐛 when bridge is present, send a final view update on page exit
  packages/rum-core/src/boot/startRum.spec.ts
  packages/rum-core/src/boot/startRum.ts
Labels: staging-19

#2237 🐛 [RUMF-1583][recorder] do not ignore empty text node during serialization
  packages/rum/src/domain/record/observers/mutationObserver.spec.ts
  packages/rum/src/domain/record/serialization/serializeNode.spec.ts
  packages/rum/src/domain/record/serialization/serializeNode.ts
Labels: staging-19

#2238 💥[RUMF-1554] Drop some deprecated config parameters
  packages/core/src/domain/configuration/configuration.spec.ts
  packages/core/src/domain/configuration/configuration.ts
  packages/core/src/domain/configuration/endpointBuilder.spec.ts
  packages/core/src/domain/configuration/endpointBuilder.ts
  packages/core/src/domain/configuration/transportConfiguration.spec.ts
  packages/rum-core/src/domain/configuration.spec.ts
  packages/rum-core/src/domain/configuration.ts
  performances/src/main.ts
  test/e2e/scenario/rum/tracing.scenario.ts
Labels: staging-19

#2273 🐛 Telemetry: do not scrub staging and canary frames
  packages/core/src/domain/telemetry/telemetry.spec.ts
  packages/core/src/domain/telemetry/telemetry.ts
Labels: staging-22
