Repository DataDog/browser-sdk, pull requests merged in 2024-03, with the labels that each got.

#2634 ✨ [RUM-3349] introduce a Consent Management API
  packages/core/src/domain/session/sessionManager.spec.ts
  packages/core/src/domain/trackingConsent.spec.ts
  packages/core/src/domain/trackingConsent.ts
  packages/core/src/tools/experimentalFeatures.ts
  packages/logs/src/boot/preStartLogs.spec.ts
  packages/rum-core/src/boot/preStartRum.spec.ts
  test/e2e/scenario/trackingConsent.scenario.ts
Labels: staging-10

#2629 ✨[RUM-3255] Report the bundle sizes differences as a PR comment
  .gitlab-ci.yml
  Dockerfile
  scripts/export-bundles-sizes.js
  scripts/lib/secrets.js
  scripts/report-bundle-size/index.js
  scripts/report-bundle-size/report-as-a-pr-comment.js
  scripts/report-bundle-size/report-to-datadog.js
Labels: staging-09, staging-11

#2642 🐛 [RUM-3502] fix `fetch(url)` tracing
  packages/core/src/tools/instrumentMethod.spec.ts
  packages/core/src/tools/instrumentMethod.ts
  test/e2e/scenario/rum/tracing.scenario.ts
Labels: staging-11

#2648 ✨ [RUM-3546] Add support of PCI compliant intake for browser logs
  packages/core/src/domain/configuration/endpointBuilder.spec.ts
  packages/core/src/domain/configuration/endpointBuilder.ts
  packages/core/src/domain/telemetry/telemetryEvent.types.ts
  packages/logs/src/domain/configuration.spec.ts
  packages/logs/src/domain/configuration.ts
Labels: mergequeue-status: in_progress

#2645 ✨ [RUM-3495] Add Pr Commenter Threshold
  scripts/report-bundle-size/report-as-a-pr-comment.js
Labels: staging-12

#2657 ⚡ [RUM-2633] Optimize DOM iteration in the recorder
  packages/rum-core/src/browser/htmlDomUtils.ts
Labels: staging-12

#2655 🐛 [RUM-3598] Ignore collecting requests to logs PCI intake as RUM resources
  packages/core/src/domain/configuration/endpointBuilder.ts
  packages/core/src/domain/configuration/intakeSites.ts
  packages/core/src/domain/configuration/transportConfiguration.spec.ts
  packages/core/src/domain/configuration/transportConfiguration.ts
Labels: mergequeue-status: rejected

#2662 🐛 [RUM-3599] do not define undefined instrumented method
  packages/core/src/tools/instrumentMethod.spec.ts
  packages/core/src/tools/instrumentMethod.ts
Labels: staging-12

#2665 ✨ [RUM-3387] forward isAborted to beforeSend context
  packages/logs/src/domain/assembly.ts
  packages/logs/src/domain/lifeCycle.ts
  packages/logs/src/domain/networkError/networkErrorCollection.spec.ts
  packages/logs/src/domain/networkError/networkErrorCollection.ts
  packages/logs/src/rawLogsEvent.types.ts
  packages/rum-core/src/domain/requestCollection.ts
  packages/rum-core/src/domain/resource/resourceCollection.spec.ts
  packages/rum-core/src/domain/resource/resourceCollection.ts
  packages/rum-core/src/domainContext.types.ts
Labels: staging-13

#2671 v5.13.0
  CHANGELOG.md
  developer-extension/package.json
  lerna.json
  packages/core/package.json
  packages/logs/package.json
  packages/rum-core/package.json
  packages/rum-slim/package.json
  packages/rum/package.json
  packages/worker/package.json
  performances/package.json
  test/app/yarn.lock
  yarn.lock
Labels: mergequeue-status: in_progress

#2659 ♻️✅ Harmonize record observers
  packages/core/src/tools/utils/functionUtils.ts
  packages/rum-core/src/index.ts
  packages/rum/src/domain/record/mutationBatch.spec.ts
  packages/rum/src/domain/record/mutationBatch.ts
  packages/rum/src/domain/record/observers/focusObserver.ts
  packages/rum/src/domain/record/observers/index.ts
  packages/rum/src/domain/record/observers/mediaInteractionObserver.ts
  packages/rum/src/domain/record/observers/observers.ts
  packages/rum/src/domain/record/observers/viewportResizeObserver.ts
  packages/rum/src/domain/record/record.ts
  packages/rum/src/domain/record/recordIds.ts
  packages/rum/src/domain/record/shadowRootsController.ts
  packages/rum/src/domain/record/trackers/index.ts
  packages/rum/src/domain/record/trackers/trackFocus.spec.ts
  packages/rum/src/domain/record/trackers/trackFocus.ts
  packages/rum/src/domain/record/trackers/trackFrustration.spec.ts
  packages/rum/src/domain/record/trackers/trackFrustration.ts
  packages/rum/src/domain/record/trackers/trackInput.spec.ts
  packages/rum/src/domain/record/trackers/trackInput.ts
  packages/rum/src/domain/record/trackers/trackMediaInteraction.spec.ts
  packages/rum/src/domain/record/trackers/trackMediaInteraction.ts
  packages/rum/src/domain/record/trackers/trackMouseInteraction.spec.ts
  packages/rum/src/domain/record/trackers/trackMouseInteraction.ts
  packages/rum/src/domain/record/trackers/trackMove.spec.ts
  packages/rum/src/domain/record/trackers/trackMove.ts
  packages/rum/src/domain/record/trackers/trackMutation.spec.ts
  packages/rum/src/domain/record/trackers/trackMutation.ts
  packages/rum/src/domain/record/trackers/trackScroll.spec.ts
  packages/rum/src/domain/record/trackers/trackScroll.ts
  packages/rum/src/domain/record/trackers/trackStyleSheet.spec.ts
  packages/rum/src/domain/record/trackers/trackStyleSheet.ts
  packages/rum/src/domain/record/trackers/trackViewEnd.spec.ts
  packages/rum/src/domain/record/trackers/trackViewEnd.ts
  packages/rum/src/domain/record/trackers/trackViewportResize.spec.ts
  packages/rum/src/domain/record/trackers/trackViewportResize.ts
  packages/rum/src/domain/record/trackers/trackers.specHelper.ts
  packages/rum/src/domain/record/trackers/types.ts
Labels: staging-12

#2663 🐛 [RUM-3581] Fix the selector computation due to properties partially supported on IE
  packages/core/src/tools/utils/polyfills.spec.ts
  packages/core/src/tools/utils/polyfills.ts
  packages/rum-core/src/browser/polyfills.spec.ts
  packages/rum-core/src/browser/polyfills.ts
  packages/rum-core/src/domain/action/computeFrustration.ts
  packages/rum-core/src/domain/action/getActionNameFromElement.spec.ts
  packages/rum-core/src/domain/action/getActionNameFromElement.ts
  packages/rum-core/src/domain/getSelectorFromElement.spec.ts
  packages/rum-core/src/domain/getSelectorFromElement.ts
  packages/rum-core/src/index.ts
  packages/rum-core/test/dom.ts
  packages/rum/src/domain/record/trackers/trackInput.ts
Labels: staging-13
