Repository DataDog/browser-sdk, pull requests merged in 2024-10, with the labels that each got.

#3045 🔊 Add SDK setup telemetry
  packages/core/src/domain/telemetry/telemetry.ts
  packages/logs/package.json
  packages/rum-slim/package.json
  packages/rum/package.json
  scripts/lib/build-env.js
Labels: staging-40

#3050 🧪 add missing start_time
  packages/rum-core/src/domain/longAnimationFrame/longAnimationFrameCollection.spec.ts
  packages/rum-core/src/domain/longAnimationFrame/longAnimationFrameCollection.ts
  packages/rum-core/src/rawRumEvent.types.ts
Labels: staging-40

#3058 🐛 ignore layout shifts that happen before view start
  packages/rum-core/src/domain/view/viewMetrics/trackCumulativeLayoutShift.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/trackCumulativeLayoutShift.ts
Labels: staging-41

#2950 [RUM 5088] Reduce INP Null Target
  packages/core/test/emulate/createNewEvent.ts
  packages/rum-core/src/domain/action/interactionSelectorCache.spec.ts
  packages/rum-core/src/domain/action/interactionSelectorCache.ts
  packages/rum-core/src/domain/action/listenActionEvents.ts
  packages/rum-core/src/domain/action/trackClickActions.spec.ts
  packages/rum-core/src/domain/action/trackClickActions.ts
  packages/rum-core/src/domain/view/viewMetrics/trackInteractionToNextPaint.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/trackInteractionToNextPaint.ts
  packages/rum-core/src/index.ts
  packages/rum-core/test/createFakeClick.ts
Labels: staging-37

#3077 🐛 [RUM-6483] Investigate reducing the batch time limit for Replay
  packages/core/src/tools/experimentalFeatures.ts
  packages/rum/src/domain/segmentCollection/segmentCollection.spec.ts
  packages/rum/src/domain/segmentCollection/segmentCollection.ts
Labels: staging-42

#3080 👷 CI - assign static resources for e2e-bs job
  .gitlab-ci.yml
Labels: team:rum-browser, mergequeue-status: in_progress

#3079 👷 CI - Enable yarn strategy on the repository
  repository.datadog.yml
Labels: team:rum-browser
