Repository DataDog/browser-sdk, pull requests merged in 2024-11, with the labels that each got.

#3099 👷 [RUM-6562] Enable and rename update view name API
  packages/core/src/tools/experimentalFeatures.ts
  packages/rum-core/src/boot/preStartRum.spec.ts
  packages/rum-core/src/boot/preStartRum.ts
  packages/rum-core/src/boot/rumPublicApi.spec.ts
  packages/rum-core/src/boot/rumPublicApi.ts
  packages/rum-core/src/boot/startRum.ts
  packages/rum-core/src/domain/view/setupViewTest.specHelper.ts
  packages/rum-core/src/domain/view/trackViews.spec.ts
  packages/rum-core/src/domain/view/trackViews.ts
  test/e2e/scenario/rum/init.scenario.ts
Labels: staging-45

#3102 ⚡️ [RUM-6929] delay resource collection
  packages/core/src/index.ts
  packages/core/src/tools/requestIdleCallback.spec.ts
  packages/core/src/tools/requestIdleCallback.ts
  packages/core/src/tools/taskQueue.spec.ts
  packages/core/src/tools/taskQueue.ts
  packages/core/test/emulate/mockRequestIdleCallback.ts
  packages/core/test/index.ts
  packages/rum-core/src/domain/resource/resourceCollection.spec.ts
  packages/rum-core/src/domain/resource/resourceCollection.ts
  packages/rum/src/domain/record/mutationBatch.spec.ts
  packages/rum/src/domain/record/mutationBatch.ts
Labels: staging-44

#3147 🐛 skip worker timing when no worker is used
  packages/rum-core/src/domain/resource/resourceUtils.spec.ts
  packages/rum-core/src/domain/resource/resourceUtils.ts
Labels: staging-47

#3115 ✨ [RUM-6956] Add action name source
  packages/core/src/tools/experimentalFeatures.ts
  packages/rum-core/src/domain/action/actionCollection.spec.ts
  packages/rum-core/src/domain/action/actionCollection.ts
  packages/rum-core/src/domain/action/getActionNameFromElement.spec.ts
  packages/rum-core/src/domain/action/getActionNameFromElement.ts
  packages/rum-core/src/domain/action/trackClickActions.spec.ts
  packages/rum-core/src/domain/action/trackClickActions.ts
  packages/rum-core/src/rawRumEvent.types.ts
  test/e2e/scenario/rum/actions.scenario.ts
Labels: staging-45, staging-46, staging-47

#3144 🐛 [RUM-87] AddError should support Error instances coming from other JS contexts
  packages/core/src/domain/console/consoleObservable.ts
  packages/core/src/domain/error/error.spec.ts
  packages/core/src/domain/error/error.ts
  packages/core/src/domain/error/trackRuntimeError.ts
  packages/core/src/domain/telemetry/telemetry.ts
  packages/core/src/index.ts
  packages/logs/src/domain/logger.spec.ts
  packages/logs/src/domain/logger.ts
  packages/rum-core/src/domain/error/errorCollection.ts
Labels: staging-47

#3162 ✨ [RUM-6182] don't start recording automatically when replay sample is 0
  packages/rum-core/src/boot/rumPublicApi.spec.ts
  packages/rum-core/src/domain/configuration/configuration.spec.ts
  packages/rum-core/src/domain/configuration/configuration.ts
Labels: staging-48
