Repository DataDog/browser-sdk, pull requests merged in 2024-07, with the labels that each got.

#2824 ⚗️✨ [RUM-4469] introduce an experimental React integration
  LICENSE-3rdparty.csv
  eslint-local-rules/disallowSideEffects.js
  package.json
  packages/core/src/domain/error/trackRuntimeError.spec.ts
  packages/core/test/disableJasmineUncaughtExceptionTracking.ts
  packages/core/test/index.ts
  packages/core/test/leakDetection.ts
  packages/rum-react/.npmignore
  packages/rum-react/.yarnrc
  packages/rum-react/README.md
  packages/rum-react/package.json
  packages/rum-react/react-router-v6/package.json
  packages/rum-react/src/domain/error/addReactError.spec.ts
  packages/rum-react/src/domain/error/addReactError.ts
  packages/rum-react/src/domain/error/errorBoundary.spec.tsx
  packages/rum-react/src/domain/error/errorBoundary.ts
  packages/rum-react/src/domain/error/index.ts
  packages/rum-react/src/domain/reactPlugin.spec.ts
  packages/rum-react/src/domain/reactPlugin.ts
  packages/rum-react/src/domain/reactRouterV6/createRouter.spec.ts
  packages/rum-react/src/domain/reactRouterV6/createRouter.ts
  packages/rum-react/src/domain/reactRouterV6/index.ts
  packages/rum-react/src/domain/reactRouterV6/routesComponent.spec.tsx
  packages/rum-react/src/domain/reactRouterV6/routesComponent.ts
  packages/rum-react/src/domain/reactRouterV6/startReactRouterView.spec.ts
  packages/rum-react/src/domain/reactRouterV6/startReactRouterView.ts
  packages/rum-react/src/domain/reactRouterV6/useRoutes.spec.tsx
  packages/rum-react/src/domain/reactRouterV6/useRoutes.ts
  packages/rum-react/src/entries/main.ts
  packages/rum-react/src/entries/reactRouterV6.ts
  packages/rum-react/test/appendComponent.ts
  packages/rum-react/test/initializeReactPlugin.ts
  packages/rum-react/tsconfig.cjs.json
  packages/rum-react/tsconfig.esm.json
  sandbox/react-app/main.tsx
  scripts/dev-server.js
  test/unit/karma.base.conf.js
  test/unit/karma.bs.conf.js
  test/unit/karma.local.conf.js
  tsconfig.base.json
  webpack.base.js
  yarn.lock
Labels: staging-26

#2841 ♻️ [RUM-66] Specialise constant files
  developer-extension/src/background/domain/syncRules.ts
  developer-extension/src/common/intakeDomainConstants.ts
  developer-extension/src/common/packagesUrlConstants.ts
  developer-extension/src/common/panelTabConstants.ts
  developer-extension/src/common/sessionKeyConstant.ts
  developer-extension/src/content-scripts/main.ts
  developer-extension/src/panel/components/panel.tsx
  developer-extension/src/panel/hooks/useDevServerStatus.ts
  developer-extension/src/panel/hooks/useEvents/eventCollection.ts
  developer-extension/src/panel/hooks/useSettings.ts
  developer-extension/src/panel/monitoring.ts
  test/e2e/lib/framework/createTest.ts
  test/e2e/lib/helpers/configuration.ts
  test/e2e/scenario/logs.scenario.ts
  test/e2e/wdio.base.conf.ts
Labels: staging-27

#2844 🐛 [RUM-5209] provide a span id for the initial document trace
  packages/rum-core/src/domain/resource/resourceCollection.spec.ts
  packages/rum-core/src/domain/resource/resourceCollection.ts
Labels: staging-27

#2808 ✨ [RUM-4819] Add an experimental 'updateViewName' API
  packages/core/src/tools/experimentalFeatures.ts
  packages/rum-core/src/boot/preStartRum.spec.ts
  packages/rum-core/src/boot/preStartRum.ts
  packages/rum-core/src/boot/rumPublicApi.spec.ts
  packages/rum-core/src/boot/rumPublicApi.ts
  packages/rum-core/src/boot/startRum.ts
  packages/rum-core/src/domain/view/setupViewTest.specHelper.ts
  packages/rum-core/src/domain/view/trackViews.spec.ts
  packages/rum-core/src/domain/view/trackViews.ts
  test/e2e/scenario/rum/init.scenario.ts
Labels: staging-27

#2834 🎨 Instrument fetch and XHR before trying to init consent
  packages/core/src/browser/fetchObservable.ts
  packages/core/src/index.ts
  packages/logs/src/boot/preStartLogs.spec.ts
  packages/logs/src/boot/preStartLogs.ts
  packages/rum-core/src/boot/preStartRum.spec.ts
  packages/rum-core/src/boot/preStartRum.ts
Labels: staging-26

#2845 ♻️ [RUM-67] Specialise type files
  developer-extension/src/background/devtoolsPanelConnection.ts
  developer-extension/src/background/domain/syncRules.ts
  developer-extension/src/common/extension.types.ts
  developer-extension/src/content-scripts/main.ts
  developer-extension/src/panel/backgroundScriptConnection.ts
  developer-extension/src/panel/components/panel.tsx
  developer-extension/src/panel/components/tabs/settingsTab.tsx
  developer-extension/src/panel/hooks/useEvents/eventCollection.ts
  developer-extension/src/panel/hooks/useEvents/useEvents.ts
  developer-extension/src/panel/hooks/useNetworkRules.ts
  developer-extension/src/panel/hooks/useSettings.ts
  developer-extension/src/panel/sessionReplayPlayer/sessionReplayPlayer.types.ts
  developer-extension/src/panel/sessionReplayPlayer/startSessionReplayPlayer.ts
  packages/core/src/browser/addEventListener.ts
  packages/core/src/browser/browser.types.ts
  packages/core/src/domain/deflate/deflate.types.ts
  packages/core/src/domain/deflate/index.ts
  packages/core/src/index.ts
  packages/rum/src/domain/record/trackers/index.ts
  packages/rum/src/domain/record/trackers/trackFocus.spec.ts
  packages/rum/src/domain/record/trackers/trackFocus.ts
  packages/rum/src/domain/record/trackers/trackFrustration.spec.ts
  packages/rum/src/domain/record/trackers/trackFrustration.ts
  packages/rum/src/domain/record/trackers/trackInput.spec.ts
  packages/rum/src/domain/record/trackers/trackInput.ts
  packages/rum/src/domain/record/trackers/trackMediaInteraction.spec.ts
  packages/rum/src/domain/record/trackers/trackMediaInteraction.ts
  packages/rum/src/domain/record/trackers/trackMouseInteraction.spec.ts
  packages/rum/src/domain/record/trackers/trackMouseInteraction.ts
  packages/rum/src/domain/record/trackers/trackMove.spec.ts
  packages/rum/src/domain/record/trackers/trackMove.ts
  packages/rum/src/domain/record/trackers/trackMutation.ts
  packages/rum/src/domain/record/trackers/trackScroll.spec.ts
  packages/rum/src/domain/record/trackers/trackScroll.ts
  packages/rum/src/domain/record/trackers/trackStyleSheet.spec.ts
  packages/rum/src/domain/record/trackers/trackStyleSheet.ts
  packages/rum/src/domain/record/trackers/trackViewEnd.spec.ts
  packages/rum/src/domain/record/trackers/trackViewEnd.ts
  packages/rum/src/domain/record/trackers/trackViewportResize.spec.ts
  packages/rum/src/domain/record/trackers/trackViewportResize.ts
  packages/rum/src/domain/record/trackers/tracker.types.ts
  performances/src/format.ts
  performances/src/main.ts
  performances/src/profilers/profilingUtils.ts
  performances/src/profilers/startCpuProfiling.ts
  performances/src/profilers/startMemoryProfiling.ts
  performances/src/profilers/startNetworkProfiling.ts
  performances/src/profilers/startProfiling.ts
  performances/src/profiling.types.ts
  performances/src/proxy.ts
  performances/src/scenarios/twitterScenario.ts
  performances/src/scenarios/wikipediaScenario.ts
Labels: staging-28

#2818 ♻️ [RUM-958] Use a performance observable instead of the lifecycle
  packages/core/src/tools/observable.spec.ts
  packages/core/src/tools/observable.ts
  packages/rum-core/src/boot/startRum.spec.ts
  packages/rum-core/src/boot/startRum.ts
  packages/rum-core/src/browser/performanceCollection.spec.ts
  packages/rum-core/src/browser/performanceCollection.ts
  packages/rum-core/src/browser/performanceObservable.spec.ts
  packages/rum-core/src/browser/performanceObservable.ts
  packages/rum-core/src/domain/lifeCycle.ts
  packages/rum-core/src/domain/longTask/longTaskCollection.spec.ts
  packages/rum-core/src/domain/longTask/longTaskCollection.ts
  packages/rum-core/src/domain/resource/matchRequestTiming.spec.ts
  packages/rum-core/src/domain/resource/matchRequestTiming.ts
  packages/rum-core/src/domain/resource/resourceCollection.spec.ts
  packages/rum-core/src/domain/resource/resourceCollection.ts
  packages/rum-core/src/domain/resource/resourceUtils.spec.ts
  packages/rum-core/src/domain/resource/resourceUtils.ts
  packages/rum-core/src/domain/resource/retrieveInitialDocumentResourceTiming.spec.ts
  packages/rum-core/src/domain/resource/retrieveInitialDocumentResourceTiming.ts
  packages/rum-core/src/domain/view/trackViews.spec.ts
  packages/rum-core/src/domain/view/trackViews.ts
  packages/rum-core/src/domain/view/viewMetrics/interactionCountPolyfill.ts
  packages/rum-core/src/domain/view/viewMetrics/trackCumulativeLayoutShift.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/trackCumulativeLayoutShift.ts
  packages/rum-core/src/domain/view/viewMetrics/trackFirstContentfulPaint.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/trackFirstContentfulPaint.ts
  packages/rum-core/src/domain/view/viewMetrics/trackFirstInput.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/trackFirstInput.ts
  packages/rum-core/src/domain/view/viewMetrics/trackInitialViewMetrics.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/trackInteractionToNextPaint.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/trackInteractionToNextPaint.ts
  packages/rum-core/src/domain/view/viewMetrics/trackLargestContentfulPaint.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/trackLargestContentfulPaint.ts
  packages/rum-core/src/domain/view/viewMetrics/trackLoadingTime.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/trackNavigationTimings.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/trackNavigationTimings.ts
  packages/rum-core/src/domain/waitPageActivityEnd.spec.ts
  packages/rum-core/src/domain/waitPageActivityEnd.ts
  packages/rum-core/test/emulate/mockPerformanceObserver.ts
  packages/rum-core/test/fixtures.ts
  packages/rum-core/test/index.ts
  packages/rum-core/test/testSetupBuilder.ts
Labels: staging-27

#2851 ♻️ [RUM-159] Categorize changes as public or internal in the CHANGELOG
  scripts/release/generate-changelog.js
Labels: staging-28

#2853 🐛 Fix update view name api in context history
  packages/rum-core/src/domain/contexts/viewContexts.spec.ts
  packages/rum-core/src/domain/contexts/viewContexts.ts
  test/e2e/scenario/rum/init.scenario.ts
Labels: staging-28

#2867 🐛 Update path for contributing and changelog file
  scripts/release/generate-changelog.js
Labels: staging-29

#2877 ⚡️Reduce bundle size: simplify config, use const enum, remove str redundancies
  packages/core/src/browser/addEventListener.ts
  packages/core/src/domain/configuration/configuration.spec.ts
  packages/core/src/domain/configuration/configuration.ts
  packages/core/src/domain/configuration/index.ts
  packages/core/src/domain/configuration/tags.ts
  packages/core/src/domain/context/customerDataTracker.ts
  packages/core/src/index.ts
  packages/core/src/tools/display.ts
  packages/core/src/transport/batch.ts
  packages/rum-core/src/domain/configuration/configuration.ts
  test/e2e/lib/framework/createTest.ts
  test/e2e/lib/framework/pageSetups.ts
Labels: staging-30

#2875 ⚡ Performance Friday Reduce Bundle Size
  packages/core/src/domain/error/error.ts
  packages/core/src/tools/serialisation/sanitize.ts
  packages/core/src/transport/startBatchWithReplica.ts
  packages/core/test/interceptRequests.ts
  packages/logs/src/domain/assembly.ts
  packages/rum-core/src/boot/rumPublicApi.ts
  packages/rum-core/src/browser/performanceObservable.ts
  packages/rum-core/src/browser/polyfills.ts
  packages/rum-core/src/domain/assembly.ts
  packages/rum-core/src/domain/view/trackViews.ts
  packages/rum-core/test/testSetupBuilder.ts
  packages/rum/src/boot/recorderApi.ts
  packages/rum/src/domain/record/trackers/trackFrustration.ts
  packages/rum/src/domain/record/trackers/trackMutation.ts
Labels: staging-30

#2855 ♻️ [RUM-5294] Use performanceObserver for navigation entries
  packages/rum-core/src/boot/startRum.spec.ts
  packages/rum-core/src/browser/performanceCollection.spec.ts
  packages/rum-core/src/browser/performanceCollection.ts
  packages/rum-core/src/browser/performanceObservable.ts
  packages/rum-core/src/browser/performanceUtils.ts
  packages/rum-core/src/domain/longTask/longTaskCollection.spec.ts
  packages/rum-core/src/domain/resource/resourceCollection.spec.ts
  packages/rum-core/src/domain/resource/resourceCollection.ts
  packages/rum-core/src/domain/resource/resourceUtils.ts
  packages/rum-core/src/domain/resource/retrieveInitialDocumentResourceTiming.spec.ts
  packages/rum-core/src/domain/resource/retrieveInitialDocumentResourceTiming.ts
  packages/rum-core/src/domain/view/trackViews.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/trackInitialViewMetrics.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/trackInitialViewMetrics.ts
  packages/rum-core/src/domain/view/viewMetrics/trackNavigationTimings.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/trackNavigationTimings.ts
  packages/rum-core/test/emulate/mockPerformanceObserver.ts
Labels: staging-28

#2899 🐛 fix unexpected exception when no entry type is supported in PerformanceObserver
  packages/rum-core/src/browser/performanceCollection.spec.ts
  packages/rum-core/src/browser/performanceCollection.ts
  packages/rum-core/src/browser/performanceObservable.spec.ts
  packages/rum-core/src/browser/performanceObservable.ts
  packages/rum-core/test/emulate/mockPerformanceObserver.ts
Labels: staging-30

#2884 🧪 Update browser matrix for tests
  packages/core/src/browser/fetchObservable.spec.ts
  packages/core/src/domain/error/trackRuntimeError.spec.ts
  packages/core/src/tools/instrumentMethod.spec.ts
  packages/core/src/tools/instrumentMethod.ts
  packages/core/src/tools/serialisation/sanitize.spec.ts
  packages/core/test/emulate/mockStorages.ts
  packages/logs/src/domain/networkError/networkErrorCollection.spec.ts
  packages/rum-core/src/domain/requestCollection.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/trackCumulativeLayoutShift.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/trackCumulativeLayoutShift.ts
  packages/rum-react/src/domain/reactRouterV6/createRouter.spec.ts
  packages/rum/src/domain/record/trackers/trackViewportResize.spec.ts
  test/browsers.conf.d.ts
  test/e2e/browsers.conf.js
  test/e2e/wdio.bs.conf.ts
  test/unit/browsers.conf.js
  test/unit/karma.bs.conf.js
Labels: staging-31
