Repository DataDog/browser-sdk, pull requests merged in 2024-06, with the labels that each got.

#2774 👷 Add extension usage tips doc and link in ui
  developer-extension/README.md
  developer-extension/src/panel/components/panel.module.css
  developer-extension/src/panel/components/panel.tsx
Labels: editorial review

#2791 [RUM-4652] Update url after playground changes
  scripts/performance/cpu-performance/compute-cpu-performance.js
  scripts/performance/memory-performance/compute-memory-performance.js
Labels: staging-23

#2777 ✨ [RUM-3837] Force Replay recording on sampled-out sessions
  developer-extension/src/panel/components/tabs/infosTab.tsx
  developer-extension/src/panel/components/tabs/replayTab.tsx
  developer-extension/src/panel/hooks/useSdkInfos.ts
  packages/core/src/domain/session/sessionManager.spec.ts
  packages/core/src/domain/session/sessionManager.ts
  packages/core/src/domain/session/sessionStore.spec.ts
  packages/core/src/domain/session/sessionStore.ts
  packages/rum-core/src/boot/rumPublicApi.ts
  packages/rum-core/src/domain/assembly.ts
  packages/rum-core/src/domain/rumSessionManager.spec.ts
  packages/rum-core/src/domain/rumSessionManager.ts
  packages/rum-core/src/index.ts
  packages/rum-core/test/mockRumSessionManager.ts
  packages/rum/src/boot/recorderApi.spec.ts
  packages/rum/src/boot/recorderApi.ts
  packages/rum/src/domain/getSessionReplayLink.spec.ts
  packages/rum/src/domain/getSessionReplayLink.ts
  test/e2e/scenario/recorder/recorder.scenario.ts
Labels: staging-22

#2794 🐛 [RUM-4178] Update performance difference memory
  scripts/performance/memory-performance/compute-memory-performance.js
  scripts/performance/report-as-a-pr-comment.js
Labels: staging-23

#2725 ✨ [RUM-1310] Support all log statuses
  developer-extension/src/panel/components/tabs/eventsTab/eventRow.tsx
  packages/logs/src/domain/logger.ts
  packages/logs/src/domain/logger/loggerCollection.spec.ts
  packages/logs/src/domain/logger/loggerCollection.ts
  packages/logs/src/logsEvent.types.ts
Labels: staging-18

#2786 ✨ [RUM-4014] DD_LOGS: add handling stack in beforeSend context
  packages/core/src/domain/console/consoleObservable.ts
  packages/logs/src/boot/logsPublicApi.spec.ts
  packages/logs/src/boot/logsPublicApi.ts
  packages/logs/src/boot/preStartLogs.spec.ts
  packages/logs/src/boot/preStartLogs.ts
  packages/logs/src/boot/startLogs.spec.ts
  packages/logs/src/domain/assembly.spec.ts
  packages/logs/src/domain/console/consoleCollection.spec.ts
  packages/logs/src/domain/console/consoleCollection.ts
  packages/logs/src/domain/logger.spec.ts
  packages/logs/src/domain/logger.ts
  packages/logs/src/domain/logger/isAuthorized.ts
  packages/logs/src/domain/logger/loggerCollection.spec.ts
  packages/logs/src/domain/logger/loggerCollection.ts
  packages/logs/src/domain/networkError/networkErrorCollection.spec.ts
  packages/logs/src/domain/networkError/networkErrorCollection.ts
  packages/logs/src/domain/report/reportCollection.spec.ts
  packages/logs/src/domain/report/reportCollection.ts
  packages/logs/src/domain/reportError.ts
  packages/logs/src/domain/runtimeError/runtimeErrorCollection.spec.ts
  packages/logs/src/domain/runtimeError/runtimeErrorCollection.ts
  packages/logs/src/domainContext.types.ts
  packages/logs/src/entries/main.ts
  packages/logs/src/rawLogsEvent.types.ts
  test/e2e/lib/framework/createTest.ts
  test/e2e/lib/framework/pageSetups.ts
  test/e2e/scenario/microfrontend.scenario.ts
Labels: staging-24

#2799 ⚗️[RUM-4780] Remote configuration
  packages/core/src/browser/addEventListener.ts
  packages/core/src/tools/experimentalFeatures.ts
  packages/core/src/transport/eventBridge.ts
  packages/core/test/requests.ts
  packages/rum-core/src/boot/preStartRum.spec.ts
  packages/rum-core/src/boot/preStartRum.ts
  packages/rum-core/src/domain/configuration/configuration.spec.ts
  packages/rum-core/src/domain/configuration/configuration.ts
  packages/rum-core/src/domain/configuration/index.ts
  packages/rum-core/src/domain/configuration/remoteConfiguration.spec.ts
  packages/rum-core/src/domain/configuration/remoteConfiguration.ts
  packages/rum-core/src/index.ts
Labels: staging-24

#2797 [RUM-4895] Add link to playground with pr's bundle
  scripts/performance/report-as-a-pr-comment.js
Labels: staging-24

#2798 Use the same service/version type in `init()` and `startView()`
  packages/rum-core/src/domain/view/trackViews.spec.ts
  packages/rum-core/src/domain/view/trackViews.ts
Labels: staging-24
