Repository DataDog/browser-sdk, pull requests merged in 2024-04, with the labels that each got.

#2639 [ci-visibility] Implement driver-agnostic integration with CI Visibility
  packages/core/src/browser/addEventListener.ts
  packages/core/src/browser/types.ts
  packages/core/src/index.ts
  packages/rum-core/src/boot/startRum.ts
  packages/rum-core/src/browser/cookieObservable.spec.ts
  packages/rum-core/src/browser/cookieObservable.ts
  packages/rum-core/src/domain/assembly.spec.ts
  packages/rum-core/src/domain/assembly.ts
  packages/rum-core/src/domain/contexts/ciTestContext.spec.ts
  packages/rum-core/src/domain/contexts/ciTestContext.ts
  packages/rum-core/src/domain/contexts/ciVisibilityContext.spec.ts
  packages/rum-core/src/domain/contexts/ciVisibilityContext.ts
  packages/rum-core/test/index.ts
  packages/rum-core/test/mockCiVisibilityValues.ts
  packages/rum-core/test/mockCiVisibilityWindowValues.ts
Labels: staging-14

#2686 🐛 fix beforeSend type definition for logs
  packages/logs/src/domain/configuration.ts
  packages/logs/src/domain/lifeCycle.ts
  packages/logs/src/domain/networkError/networkErrorCollection.ts
  packages/logs/src/domainContext.types.ts
Labels: staging-14

#2701 ⚡️ [RUM-3283] Do not fetch the entire git history in report-bundle-size
  scripts/report-bundle-size/report-as-a-pr-comment.js
Labels: staging-15

#2690 ✨ [RUM-162] Truncate resources URL containing data URLs
  packages/rum-core/src/domain/resource/resourceCollection.ts
  packages/rum-core/src/domain/resource/resourceUtils.spec.ts
  packages/rum-core/src/domain/resource/resourceUtils.ts
  packages/rum-core/src/index.ts
  packages/rum/src/domain/record/privacy.ts
  packages/rum/src/domain/record/serialization/serializeAttribute.spec.ts
  packages/rum/src/domain/record/serialization/serializeAttribute.ts
Labels: staging-14, staging-15

#2688 ⚗ [RUM-2782] validate resource timings more granularly
  packages/core/src/tools/experimentalFeatures.ts
  packages/rum-core/src/domain/resource/matchRequestTiming.spec.ts
  packages/rum-core/src/domain/resource/resourceUtils.spec.ts
  packages/rum-core/src/domain/resource/resourceUtils.ts
Labels: staging-14

#2714 🐛[RUM-4109] Mask iframe srcdoc with privacy override
  packages/rum/src/domain/record/serialization/serializeAttribute.spec.ts
  packages/rum/src/domain/record/serialization/serializeAttribute.ts
Labels: staging-16

#2721 🔨 Update no pull request case for cpu performance
  scripts/performance/cpu-performance/compute-cpu-performance.js
Labels: staging-17

#2673 ✨ [RUM-3710] Update session ID handling to support cookie deletion
  developer-extension/src/panel/components/tabs/infosTab.tsx
  packages/core/src/domain/session/README.md
  packages/core/src/domain/session/oldCookiesMigration.ts
  packages/core/src/domain/session/sessionManager.spec.ts
  packages/core/src/domain/session/sessionManager.ts
  packages/core/src/domain/session/sessionState.spec.ts
  packages/core/src/domain/session/sessionState.ts
  packages/core/src/domain/session/sessionStore.spec.ts
  packages/core/src/domain/session/sessionStore.ts
  packages/core/src/domain/session/sessionStoreOperations.spec.ts
  packages/core/src/domain/session/sessionStoreOperations.ts
  packages/core/src/domain/session/storeStrategies/sessionInCookie.spec.ts
  packages/core/src/domain/session/storeStrategies/sessionInCookie.ts
  packages/core/src/domain/session/storeStrategies/sessionInLocalStorage.spec.ts
  packages/core/src/domain/session/storeStrategies/sessionInLocalStorage.ts
  packages/core/src/domain/session/storeStrategies/sessionStoreStrategy.ts
  packages/logs/src/domain/logsSessionManager.spec.ts
  packages/rum-core/src/domain/rumSessionManager.spec.ts
  test/e2e/lib/helpers/browser.ts
  test/e2e/lib/helpers/session.ts
  test/e2e/scenario/recorder/shadowDom.scenario.ts
  test/e2e/scenario/recorder/viewports.scenario.ts
  test/e2e/scenario/rum/sessions.scenario.ts
  test/e2e/scenario/trackingConsent.scenario.ts
Labels: staging-14, staging-15
