Repository DataDog/browser-sdk, pull requests merged in 2024-09, with the labels that each got.

#2947 🐛 [RUM-5920] Fix tags format warning
  packages/core/src/domain/configuration/tags.spec.ts
  packages/core/src/domain/configuration/tags.ts
Labels: staging-34

#2968 🐛 Allow both history and History prototype to be patched by 3rd party
  packages/core/test/emulate/buildLocation.ts
  packages/core/test/emulate/mockLocation.ts
  packages/core/test/index.ts
  packages/rum-core/src/browser/locationChangeObservable.spec.ts
  packages/rum-core/src/browser/locationChangeObservable.ts
Labels: staging-36

#2958 🐛 [RUM-94] ignore performance resource timings with negative duration
  packages/rum-core/src/browser/performanceObservable.spec.ts
  packages/rum-core/src/browser/performanceObservable.ts
  packages/rum-core/src/domain/resource/matchRequestResourceEntry.spec.ts
  packages/rum-core/src/domain/resource/matchRequestResourceEntry.ts
  packages/rum-core/src/domain/resource/resourceCollection.ts
  packages/rum-core/src/domain/resource/resourceUtils.spec.ts
  packages/rum-core/src/domain/resource/resourceUtils.ts
  packages/rum-core/src/rawRumEvent.types.ts
Labels: staging-35

#2989 ♻️ [RUM-6180] Use performanceObserver for long-task entries
  packages/rum-core/src/boot/startRum.spec.ts
  packages/rum-core/src/browser/performanceCollection.spec.ts
  packages/rum-core/src/browser/performanceCollection.ts
  packages/rum-core/src/domain/longTask/longTaskCollection.spec.ts
  packages/rum-core/src/domain/longTask/longTaskCollection.ts
Labels: staging-38

#2994 🐛 convert long animation frame times to nanoseconds
  packages/rum-core/src/domain/longAnimationFrame/longAnimationFrameCollection.spec.ts
  packages/rum-core/src/domain/longAnimationFrame/longAnimationFrameCollection.ts
  packages/rum-core/src/rawRumEvent.types.ts
Labels: staging-38

#2996 🔥 cleanup unused Experimental Features
  packages/core/src/tools/experimentalFeatures.ts
  packages/rum-core/src/domain/resource/matchRequestResourceEntry.spec.ts
  packages/rum-core/src/domain/resource/resourceUtils.spec.ts
  packages/rum-core/src/domain/resource/resourceUtils.ts
Labels: staging-38

#2964 🐛 [RUM-5785] fix missing navigation timings on Safari
  packages/core/src/browser/runOnReadyState.ts
  packages/rum-core/src/boot/startRum.spec.ts
  packages/rum-core/src/browser/performanceObservable.spec.ts
  packages/rum-core/src/browser/performanceObservable.ts
  packages/rum-core/src/browser/performanceUtils.spec.ts
  packages/rum-core/src/browser/performanceUtils.ts
  packages/rum-core/src/domain/resource/matchRequestResourceEntry.spec.ts
  packages/rum-core/src/domain/resource/retrieveInitialDocumentResourceTiming.ts
  packages/rum-core/src/domain/view/setupViewTest.specHelper.ts
  packages/rum-core/src/domain/view/trackViews.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/trackInitialViewMetrics.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/trackNavigationTimings.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/trackNavigationTimings.ts
  packages/rum-core/test/emulate/mockDocumentReadyState.ts
  packages/rum-core/test/emulate/mockGlobalPerformanceBuffer.ts
  packages/rum-core/test/emulate/mockPerformanceObserver.ts
  packages/rum-core/test/index.ts
  packages/rum/src/boot/recorderApi.spec.ts
Labels: mergequeue-status: in_progress, staging-36, staging-38
