Repository DataDog/browser-sdk, pull requests merged in 2024-02, with the labels that each got.

#2579 ⚡️ [RUM-2917] optimize getNodePrivacyLevel by adding a cache
  packages/rum/src/domain/record/observers/mutationObserver.ts
  packages/rum/src/domain/record/privacy.spec.ts
  packages/rum/src/domain/record/privacy.ts
Labels: staging-05

#2575 ♻️ [RUM-2445] split RUM and Logs public APIs modules
  packages/core/src/boot/displayAlreadyInitializedError.spec.ts
  packages/core/src/boot/displayAlreadyInitializedError.ts
  packages/core/src/index.ts
  packages/core/src/tools/boundedBuffer.spec.ts
  packages/core/src/tools/boundedBuffer.ts
  packages/core/src/tools/utils/arrayUtils.ts
  packages/core/src/tools/valueHistory.ts
  packages/logs/src/boot/logsPublicApi.spec.ts
  packages/logs/src/boot/logsPublicApi.ts
  packages/logs/src/boot/preStartLogs.spec.ts
  packages/logs/src/boot/preStartLogs.ts
  packages/logs/src/boot/startLogs.ts
  packages/rum-core/src/boot/preStartRum.spec.ts
  packages/rum-core/src/boot/preStartRum.ts
  packages/rum-core/src/boot/rumPublicApi.spec.ts
  packages/rum-core/src/boot/rumPublicApi.ts
  packages/rum-core/src/boot/startRum.ts
  packages/rum-core/src/index.ts
  packages/rum/test/mockWorker.ts
Labels: staging-03, staging-05

#2589 ⚗️✨ [RUM-2445] implement Tracking Consent management
  packages/core/src/domain/configuration/configuration.spec.ts
  packages/core/src/domain/configuration/configuration.ts
  packages/core/src/domain/session/sessionManager.spec.ts
  packages/core/src/domain/session/sessionManager.ts
  packages/core/src/domain/trackingConsent.spec.ts
  packages/core/src/domain/trackingConsent.ts
  packages/core/src/index.ts
  packages/core/src/tools/experimentalFeatures.ts
  packages/logs/src/boot/logsPublicApi.ts
  packages/logs/src/boot/preStartLogs.spec.ts
  packages/logs/src/boot/preStartLogs.ts
  packages/logs/src/boot/startLogs.spec.ts
  packages/logs/src/boot/startLogs.ts
  packages/logs/src/domain/logsSessionManager.spec.ts
  packages/logs/src/domain/logsSessionManager.ts
  packages/rum-core/src/boot/preStartRum.spec.ts
  packages/rum-core/src/boot/preStartRum.ts
  packages/rum-core/src/boot/rumPublicApi.ts
  packages/rum-core/src/boot/startRum.spec.ts
  packages/rum-core/src/boot/startRum.ts
  packages/rum-core/src/domain/rumSessionManager.spec.ts
  packages/rum-core/src/domain/rumSessionManager.ts
  test/e2e/scenario/trackingConsent.scenario.ts
Labels: staging-06

#2605 ✨[RUM-3151] Report bundle sizes to logs
  .gitlab-ci.yml
  scripts/export-bundles-sizes.js
  scripts/lib/browser-sdk-version.js
  scripts/lib/build-env.js
  scripts/lib/execution-utils.js
  scripts/release/generate-changelog.js
  scripts/release/update-peer-dependency-versions.js
Labels: staging-07

#2598 🐛 [RUM-3039] Fix missing pending mutations at view end
  packages/core/src/domain/session/sessionManager.spec.ts
  packages/core/src/domain/session/sessionManager.ts
  packages/core/src/tools/instrumentMethod.spec.ts
  packages/core/src/tools/instrumentMethod.ts
  packages/rum-core/src/domain/contexts/featureFlagContext.spec.ts
  packages/rum-core/src/domain/contexts/featureFlagContext.ts
  packages/rum-core/src/domain/contexts/urlContexts.spec.ts
  packages/rum-core/src/domain/contexts/urlContexts.ts
  packages/rum-core/src/domain/contexts/viewContexts.spec.ts
  packages/rum-core/src/domain/contexts/viewContexts.ts
  packages/rum-core/src/domain/lifeCycle.ts
  packages/rum-core/src/domain/view/trackViews.spec.ts
  packages/rum-core/src/domain/view/trackViews.ts
  packages/rum-core/src/index.ts
  packages/rum/src/boot/recorderApi.spec.ts
  packages/rum/src/boot/recorderApi.ts
  packages/rum/src/boot/startRecording.spec.ts
  packages/rum/src/domain/record/observers/moveObserver.ts
  packages/rum/src/domain/record/observers/scrollObserver.ts
  packages/rum/src/domain/record/observers/viewportResizeObserver.ts
  packages/rum/src/domain/record/record.ts
Labels: staging-07

#2615 👷 Fix ip package vulnerability by bumping dependant packages
  yarn.lock
Labels: mergequeue-status: in_progress

#2624 v5.10.0
  CHANGELOG.md
  developer-extension/package.json
  lerna.json
  packages/core/package.json
  packages/logs/package.json
  packages/rum-core/package.json
  packages/rum-slim/package.json
  packages/rum/package.json
  packages/worker/package.json
  performances/package.json
  test/app/yarn.lock
  yarn.lock
Labels: mergequeue-status: in_progress
