Repository DataDog/browser-sdk, pull requests merged in 2024-05, with the labels that each got.

#2744 🐛 [RUM-97] Sanitize tags parameter in configuration
  packages/core/src/domain/configuration/configuration.spec.ts
  packages/core/src/domain/configuration/configuration.ts
Labels: staging-20

#2746 🔊 Deduplicate telemetry events
  packages/core/src/domain/telemetry/telemetry.spec.ts
  packages/core/src/domain/telemetry/telemetry.ts
  packages/logs/src/domain/configuration.spec.ts
Labels: staging-19

#2755 🔊 collect pre start telemetry
  packages/core/src/domain/telemetry/index.ts
  packages/core/src/domain/telemetry/telemetry.spec.ts
  packages/core/src/domain/telemetry/telemetry.ts
  packages/core/src/index.ts
  packages/logs/src/domain/logsTelemetry.ts
  packages/rum-core/src/boot/startRum.ts
Labels: staging-20

#2749 🐛 [RUM-4436] fix detached node memory leak on CLS
  packages/core/src/browser/types.ts
  packages/core/src/index.ts
  packages/rum-core/src/domain/view/viewMetrics/trackCumulativeLayoutShift.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/trackCumulativeLayoutShift.ts
Labels: staging-20

#2747 🐛 [RUM-4434] fix timing matching for the same resource requested twice at the same time
  packages/rum-core/src/browser/polyfills.spec.ts
  packages/rum-core/src/browser/polyfills.ts
  packages/rum-core/src/domain/resource/matchRequestTiming.spec.ts
  packages/rum-core/src/domain/resource/matchRequestTiming.ts
  packages/rum-core/src/domain/resource/resourceUtils.ts
  test/e2e/scenario/rum/resources.scenario.ts
Labels: staging-20

#2764 🐛 [RUM-1666] Don't set negative action loading time
  packages/rum-core/src/domain/action/actionCollection.spec.ts
  packages/rum-core/src/domain/action/actionCollection.ts
  packages/rum-core/src/domain/discardNegativeDuration.ts
  packages/rum-core/src/domain/view/viewCollection.ts
Labels: staging-21

#2768 🔥 Cleanup experimental features
  packages/core/src/browser/pageExitObservable.spec.ts
  packages/core/src/browser/pageExitObservable.ts
  packages/core/src/domain/configuration/endpointBuilder.spec.ts
  packages/core/src/domain/configuration/endpointBuilder.ts
  packages/core/src/tools/experimentalFeatures.ts
  packages/core/src/transport/batch.spec.ts
  packages/core/src/transport/batch.ts
  packages/core/src/transport/httpRequest.ts
  packages/rum-core/src/domain/resource/resourceCollection.spec.ts
  packages/rum-core/src/domain/resource/resourceCollection.ts
  packages/rum-core/src/domain/view/trackViews.spec.ts
  packages/rum-core/src/domain/view/trackViews.ts
  packages/rum-core/src/domain/view/viewMetrics/trackLargestContentfulPaint.ts
  packages/rum/src/boot/recorderApi.ts
  packages/rum/src/domain/record/serialization/serializeAttributes.ts
  packages/rum/src/domain/record/serialization/serializeNode.spec.ts
Labels: staging-21

#2766 🐛 [RUM-4493] do not compute selectors for detached elements
  packages/rum-core/src/domain/action/trackClickActions.ts
  packages/rum-core/src/domain/getSelectorFromElement.spec.ts
  packages/rum-core/src/domain/getSelectorFromElement.ts
  packages/rum-core/src/domain/view/viewMetrics/trackCumulativeLayoutShift.ts
Labels: staging-21

#2781 🐛 [RUM-4629] accept `null` as env/version/service
  packages/core/src/domain/configuration/configuration.spec.ts
  packages/core/src/domain/configuration/configuration.ts
  packages/rum-core/src/domain/configuration.spec.ts
  packages/rum-core/src/domain/configuration.ts
Labels: staging-21

#2769 🔥 Remove unnecessary session checks in collections
  packages/rum-core/src/boot/startRum.spec.ts
  packages/rum-core/src/boot/startRum.ts
  packages/rum-core/src/domain/longTask/longTaskCollection.spec.ts
  packages/rum-core/src/domain/longTask/longTaskCollection.ts
  packages/rum-core/src/domain/resource/resourceCollection.spec.ts
  packages/rum-core/src/domain/resource/resourceCollection.ts
Labels: staging-22

#2782 ⚡️ [RUM-4468] improve CSS selector computation performance
  packages/rum-core/src/domain/getSelectorFromElement.spec.ts
  packages/rum-core/src/domain/getSelectorFromElement.ts
Labels: staging-22, staging-21

#2785 🐛 [RUM-98] Warn when SDK is loaded multiple times
  packages/core/src/boot/init.ts
Labels: staging-22
