Repository DataDog/browser-sdk, pull requests merged in 2024-12, with the labels that each got.

#3181 ♻️ [RUM-6813] Split the recorder API module
  packages/rum/src/boot/postStartStrategy.ts
  packages/rum/src/boot/preStartStrategy.ts
  packages/rum/src/boot/recorderApi.spec.ts
  packages/rum/src/boot/recorderApi.ts
Labels: staging-49

#3206 [RUM-6075] Test anonymous id on staging behind ff
  packages/core/src/browser/cookie.ts
  packages/core/src/domain/session/sessionConstants.ts
  packages/core/src/domain/session/sessionManager.ts
  packages/core/src/domain/session/sessionState.ts
  packages/core/src/domain/session/sessionStateValidation.ts
  packages/core/src/domain/session/sessionStore.ts
  packages/core/src/domain/session/sessionStoreOperations.spec.ts
  packages/core/src/domain/session/sessionStoreOperations.ts
  packages/core/src/domain/session/storeStrategies/sessionInCookie.spec.ts
  packages/core/src/domain/session/storeStrategies/sessionInCookie.ts
  packages/core/src/domain/session/storeStrategies/sessionInLocalStorage.spec.ts
  packages/core/src/domain/session/storeStrategies/sessionInLocalStorage.ts
  packages/core/src/domain/session/storeStrategies/sessionStoreStrategy.ts
  packages/core/src/domain/user/user.spec.ts
  packages/core/src/domain/user/user.ts
  packages/core/src/index.ts
  packages/core/src/tools/experimentalFeatures.ts
  packages/core/test/emulate/mockStorages.ts
  packages/rum-core/src/domain/assembly.spec.ts
  packages/rum-core/src/domain/assembly.ts
  packages/rum-core/src/domain/rumSessionManager.ts
  packages/rum-core/test/mockRumSessionManager.ts
Labels: staging-50

#3228 🐛 AddError should support all instances of type Error
  packages/core/src/domain/error/error.ts
  packages/rum-core/src/domain/error/errorCollection.spec.ts
Labels: bug

#3209 ⚡️ [RUM-7650] Delay the viewport dimension collection
  packages/core/src/tools/experimentalFeatures.ts
  packages/rum-core/src/domain/contexts/displayContext.spec.ts
  packages/rum-core/src/domain/contexts/displayContext.ts
Labels: staging-50
