Repository DataDog/browser-sdk, pull requests merged in 2024-01, with the labels that each got.

#2553 🐛 [RUM-2689] fix recorder crash when restarted quickly
  packages/rum/src/boot/recorderApi.spec.ts
  packages/rum/src/boot/recorderApi.ts
  test/e2e/scenario/recorder/recorder.scenario.ts
Labels: staging-02

#2561 🐛 [RUM-2735] Track request with undefined/null method
  packages/core/src/browser/fetchObservable.spec.ts
  packages/core/src/browser/fetchObservable.ts
  packages/core/src/browser/xhrObservable.spec.ts
  packages/core/src/browser/xhrObservable.ts
  packages/core/test/requests.ts
Labels: staging-02

#2563 ♻️ [RUM-2445] do not buffer early recorder API calls
  packages/rum-core/src/boot/rumPublicApi.spec.ts
  packages/rum-core/src/boot/rumPublicApi.ts
  packages/rum-slim/src/boot/stubRecorderApi.ts
  packages/rum-slim/src/entries/main.ts
  packages/rum/src/boot/recorderApi.ts
Labels: staging-02

#2562 ♻️ [RUM-2445] simplify context manager sync with local storage
  packages/core/src/domain/context/storeContextManager.spec.ts
  packages/core/src/domain/context/storeContextManager.ts
  packages/core/src/domain/context/storedContextManager.spec.ts
  packages/core/src/index.ts
  packages/logs/src/boot/logsPublicApi.ts
  packages/rum-core/src/boot/rumPublicApi.ts
Labels: staging-02

#2565 🐛[RUM-2752] Replay: generate censored images with custom dimensions
  packages/rum/src/domain/record/serialization/serializationUtils.ts
  packages/rum/src/domain/record/serialization/serializeAttribute.spec.ts
  packages/rum/src/domain/record/serialization/serializeAttribute.ts
Labels: staging-02

#2576 🐛 [RUM-2940] fix normalize URL for relative paths
  packages/core/src/tools/utils/urlPolyfill.spec.ts
  packages/core/src/tools/utils/urlPolyfill.ts
  test/unit/karma.base.conf.js
Labels: staging-04

#2577 👷 Bump chrome to 121.0.6167.85-1
  .gitlab-ci.yml
Labels: mergequeue-status: removed
