Repository DataDog/browser-sdk, pull requests merged in 2025-01, with the labels that each got.

#3086 [React RUM] Add a ReactComponentTracker component
  packages/rum-react/src/domain/performance/addDurationVital.ts
  packages/rum-react/src/domain/performance/index.ts
  packages/rum-react/src/domain/performance/reactComponentTracker.spec.tsx
  packages/rum-react/src/domain/performance/reactComponentTracker.tsx
  packages/rum-react/src/domain/performance/timer.spec.ts
  packages/rum-react/src/domain/performance/timer.ts
  packages/rum-react/src/entries/main.ts
  sandbox/react-app/main.tsx
  webpack.base.js
Labels: mergequeue-status: removed

#3293 ✨ Report original error from `addReactError` instead of fake rendering error
  packages/core/src/domain/error/error.ts
  packages/core/src/domain/error/error.types.ts
  packages/logs/src/domain/createErrorFieldFromRawError.spec.ts
  packages/rum-core/src/boot/preStartRum.ts
  packages/rum-core/src/boot/rumPublicApi.ts
  packages/rum-core/src/domain/error/errorCollection.spec.ts
  packages/rum-core/src/domain/error/errorCollection.ts
  packages/rum-core/src/domain/plugins.ts
  packages/rum-core/src/index.ts
  packages/rum-core/src/rawRumEvent.types.ts
  packages/rum-react/src/domain/error/addReactError.spec.ts
  packages/rum-react/src/domain/error/addReactError.ts
  packages/rum-react/src/domain/error/errorBoundary.spec.tsx
  packages/rum-react/src/domain/performance/addDurationVital.ts
  packages/rum-react/src/domain/reactPlugin.spec.ts
  packages/rum-react/src/domain/reactPlugin.ts
  packages/rum-react/src/domain/reactRouterV6/startReactRouterView.ts
  packages/rum-react/test/initializeReactPlugin.ts
Labels: mergequeue-status: removed

#3302 🚨 enforce consistent type export
  developer-extension/src/panel/hooks/useEvents/index.ts
  eslint.config.mjs
  packages/core/src/domain/configuration/index.ts
  packages/core/src/domain/telemetry/index.ts
  packages/core/src/domain/user/index.ts
  packages/core/src/index.ts
  packages/core/src/transport/index.ts
  packages/core/test/index.ts
  packages/logs/src/entries/main.ts
  packages/rum-core/src/index.ts
  packages/rum-slim/src/entries/main.ts
  packages/rum/src/domain/deflate/index.ts
  packages/rum/src/domain/record/index.ts
  packages/rum/src/domain/record/serialization/index.ts
  packages/rum/src/domain/record/trackers/index.ts
  packages/rum/src/entries/main.ts
  packages/rum/src/types/index.ts
Labels: mergequeue-status: in_progress

#3307 🐛 fix document resource duration
  packages/rum-core/src/browser/performanceObservable.ts
  packages/rum-core/src/browser/performanceUtils.ts
  packages/rum-core/src/domain/longAnimationFrame/longAnimationFrameCollection.spec.ts
  packages/rum-core/src/domain/resource/resourceCollection.spec.ts
  packages/rum-core/src/domain/resource/retrieveInitialDocumentResourceTiming.spec.ts
  packages/rum-core/src/domain/resource/retrieveInitialDocumentResourceTiming.ts
  packages/rum-core/src/domain/view/viewMetrics/trackInteractionToNextPaint.spec.ts
  packages/rum-core/test/fixtures.ts
Labels: staging-05
