Repository DataDog/browser-sdk, pull requests merged in 2025-07, with the labels that each got.

#3567 ♻️ [RUM-10005] Exposes `addEvent` instead of `strategy` to plugins
  eslint.config.mjs
  packages/core/src/domain/error/error.types.ts
  packages/core/src/domain/resourceUtils.ts
  packages/core/src/domain/telemetry/rawTelemetryEvent.types.ts
  packages/core/src/domain/telemetry/telemetry.ts
  packages/rum-core/src/boot/rumPublicApi.spec.ts
  packages/rum-core/src/boot/rumPublicApi.ts
  packages/rum-core/src/boot/startRum.ts
  packages/rum-core/src/domain/action/actionCollection.ts
  packages/rum-core/src/domain/action/trackClickActions.ts
  packages/rum-core/src/domain/error/errorCollection.ts
  packages/rum-core/src/domain/event/eventCollection.spec.ts
  packages/rum-core/src/domain/event/eventCollection.ts
  packages/rum-core/src/domain/plugins.ts
  packages/rum-core/src/domain/resource/resourceCollection.ts
  packages/rum-core/src/domain/vital/vitalCollection.ts
  packages/rum-core/src/domainContext.types.ts
  packages/rum-core/src/index.ts
  packages/rum-core/src/rawRumEvent.types.ts
  packages/rum-react/src/domain/error/addReactError.spec.ts
  packages/rum-react/src/domain/error/addReactError.ts
  packages/rum-react/src/domain/error/errorBoundary.spec.tsx
  packages/rum-react/src/domain/reactPlugin.ts
  packages/rum-react/test/initializeReactPlugin.ts
  test/e2e/lib/framework/pageSetups.ts
  test/e2e/scenario/plugin.scenario.ts
Labels: staging-27

#3652 ✨ don't write lock to cookie for read only operation
  packages/core/src/domain/session/sessionStore.spec.ts
  packages/core/src/domain/session/sessionStore.ts
  packages/core/src/domain/session/sessionStoreOperations.spec.ts
  packages/core/test/fakeSessionStoreStrategy.ts
  packages/core/test/index.ts
Labels: staging-28

#3685 ♻️ [RUM-10900] Introduce assemble telemetry hook
  packages/core/src/domain/contexts/rumInternalContext.type.ts
  packages/core/src/domain/contexts/userContext.spec.ts
  packages/core/src/domain/contexts/userContext.ts
  packages/core/src/domain/telemetry/telemetry.spec.ts
  packages/core/src/domain/telemetry/telemetry.ts
  packages/core/src/index.ts
  packages/core/src/tools/abstractHooks.spec.ts
  packages/core/src/tools/abstractHooks.ts
  packages/core/test/createHooks.ts
  packages/logs/src/boot/startLogs.ts
  packages/logs/src/domain/contexts/rumInternalContext.spec.ts
  packages/logs/src/domain/contexts/rumInternalContext.ts
  packages/logs/src/domain/contexts/sessionContext.spec.ts
  packages/logs/src/domain/contexts/sessionContext.ts
  packages/logs/src/domain/hooks.ts
  packages/rum-core/src/boot/rumPublicApi.ts
  packages/rum-core/src/boot/startRum.ts
  packages/rum-core/src/domain/action/actionCollection.spec.ts
  packages/rum-core/src/domain/action/actionCollection.ts
  packages/rum-core/src/domain/contexts/defaultContext.spec.ts
  packages/rum-core/src/domain/contexts/defaultContext.ts
  packages/rum-core/src/domain/contexts/internalContext.ts
  packages/rum-core/src/domain/contexts/sessionContext.spec.ts
  packages/rum-core/src/domain/contexts/sessionContext.ts
  packages/rum-core/src/domain/hooks.ts
  packages/rum-core/src/domain/view/viewCollection.spec.ts
  packages/rum-core/src/domain/view/viewCollection.ts
  packages/rum-core/src/index.ts
Labels: staging-29

#3702 👷 simplify test apps build
  package.json
  scripts/build/build-test-apps.mjs
  scripts/cli
  scripts/extensions/build-testing-extensions.js
Labels: mergequeue-status: in_progress

#3680 🐛 prevent log reporting after consent revocation
  packages/core/src/domain/telemetry/telemetry.ts
  packages/logs/src/boot/startLogs.spec.ts
  packages/logs/src/boot/startLogs.ts
  packages/logs/src/domain/contexts/trackingConsentContext.spec.ts
  packages/logs/src/domain/contexts/trackingConsentContext.ts
  packages/logs/src/domain/hooks.ts
  packages/rum-core/src/boot/startRum.ts
  packages/rum-core/src/domain/contexts/trackingConsentContext.spec.ts
  packages/rum-core/src/domain/contexts/trackingConsentContext.ts
  packages/rum-core/src/domain/hooks.ts
  test/e2e/scenario/telemetry.scenario.ts
Labels: mergequeue-status: in_progress

#3716 👷 Bump OS and device version.
  packages/rum-core/src/browser/performanceObservable.ts
  packages/rum-core/src/browser/performanceUtils.spec.ts
  test/unit/browsers.conf.js
Labels: mergequeue-status: in_progress

#3717 🔊 Add telemetry to isUnsupportedExtensionEnvironment
  packages/core/src/domain/allowedTrackingOrigins.ts
Labels: mergequeue-status: in_progress, staging-30

#3687 ✨[RUM-10825] Add hot-reload to developer-extension
  LICENSE-3rdparty.csv
  developer-extension/package.json
  developer-extension/src/panel/index.tsx
  developer-extension/webpack.config.js
  yarn.lock
Labels: mergequeue-status: in_progress

#3721 ✅ [Remote config] add a remote config e2e scenario
  packages/rum-core/src/domain/configuration/configuration.spec.ts
  packages/rum-core/src/domain/configuration/configuration.ts
  packages/rum-core/src/domain/configuration/remoteConfiguration.spec.ts
  packages/rum-core/src/domain/configuration/remoteConfiguration.ts
  packages/rum-core/src/domain/configuration/remoteConfiguration.types.ts
  packages/rum-core/src/index.ts
  remote-configuration/README.md
  remote-configuration/rum-sdk-config.json
  scripts/generate-schema-types.js
  test/e2e/lib/framework/createTest.ts
  test/e2e/lib/framework/pageSetups.ts
  test/e2e/lib/framework/serverApps/mock.ts
  test/e2e/scenario/rum/remoteConfig.scenario.ts
Labels: staging-31

#3741 👷add back html coverage report
  test/unit/karma.local.conf.js
Labels: mergequeue-status: in_progress

#3723 ♻️ use fetch to retrieve remote configuration
  packages/core/test/interceptRequests.ts
  packages/rum-core/src/boot/preStartRum.spec.ts
  packages/rum-core/src/boot/preStartRum.ts
  packages/rum-core/src/domain/configuration/remoteConfiguration.spec.ts
  packages/rum-core/src/domain/configuration/remoteConfiguration.ts
Labels: staging-31
