Repository DataDog/browser-sdk, pull requests merged in 2025-05, with the labels that each got.

#3510 [RUM Profiler] Use clocks for start/end time
  packages/rum/src/domain/profiling/profiler.ts
  packages/rum/src/domain/profiling/profilingCorrelation.ts
  packages/rum/src/domain/profiling/transport/transport.ts
  packages/rum/src/domain/profiling/types/rumProfiler.types.ts
  packages/rum/src/domain/profiling/utils/longTaskRegistry.ts
Labels: staging-18

#3498 ♻️ [RUM-9614] Decouple default context from assembly using hooks
  packages/rum-core/src/boot/startRum.ts
  packages/rum-core/src/domain/action/actionCollection.spec.ts
  packages/rum-core/src/domain/action/actionCollection.ts
  packages/rum-core/src/domain/assembly.spec.ts
  packages/rum-core/src/domain/assembly.ts
  packages/rum-core/src/domain/contexts/accountContext.spec.ts
  packages/rum-core/src/domain/contexts/accountContext.ts
  packages/rum-core/src/domain/contexts/ciVisibilityContext.spec.ts
  packages/rum-core/src/domain/contexts/ciVisibilityContext.ts
  packages/rum-core/src/domain/contexts/connectivityContext.ts
  packages/rum-core/src/domain/contexts/defaultContext.spec.ts
  packages/rum-core/src/domain/contexts/defaultContext.ts
  packages/rum-core/src/domain/contexts/displayContext.ts
  packages/rum-core/src/domain/contexts/featureFlagContext.spec.ts
  packages/rum-core/src/domain/contexts/featureFlagContext.ts
  packages/rum-core/src/domain/contexts/globalContext.ts
  packages/rum-core/src/domain/contexts/pageStateHistory.spec.ts
  packages/rum-core/src/domain/contexts/pageStateHistory.ts
  packages/rum-core/src/domain/contexts/sessionContext.spec.ts
  packages/rum-core/src/domain/contexts/sessionContext.ts
  packages/rum-core/src/domain/contexts/syntheticsContext.spec.ts
  packages/rum-core/src/domain/contexts/syntheticsContext.ts
  packages/rum-core/src/domain/contexts/urlContexts.spec.ts
  packages/rum-core/src/domain/contexts/urlContexts.ts
  packages/rum-core/src/domain/contexts/userContext.spec.ts
  packages/rum-core/src/domain/contexts/userContext.ts
  packages/rum-core/src/domain/view/viewCollection.spec.ts
  packages/rum-core/src/domain/view/viewCollection.ts
  packages/rum-core/src/hooks.spec.ts
  packages/rum-core/src/hooks.ts
Labels: staging-19

#3531 📝 mention missing `compressIntakeRequests` support in rum-slim readme
  packages/rum-slim/README.md
Labels: mergequeue-status: waiting

#3530 ✨ Allow overriding service and version for views events in beforeSend
  packages/rum-core/src/domain/assembly.spec.ts
  packages/rum-core/src/domain/assembly.ts
  test/e2e/scenario/microfrontend.scenario.ts
Labels: staging-20

#3547 👷‍♀️ [RUM-10010] Send the user, account and session using the trace baggage header
  packages/core/src/tools/experimentalFeatures.ts
  packages/rum-core/src/domain/tracing/tracer.spec.ts
  packages/rum-core/src/domain/tracing/tracer.ts
Labels: staging-21

#3561 ⚡️ [RUM-10104] avoid polling the cookie for `ciVisibilityContext`
  packages/core/src/browser/addEventListener.spec.ts
  packages/core/src/browser/browser.types.ts
  packages/rum-core/src/boot/startRum.ts
  packages/rum-core/src/browser/cookieObservable.spec.ts
  packages/rum-core/src/browser/cookieObservable.ts
  packages/rum-core/src/domain/contexts/ciVisibilityContext.spec.ts
  packages/rum-core/src/domain/contexts/ciVisibilityContext.ts
Labels: mergequeue-status: in_progress, staging-22

#3577 🔥 🐛 fix Next.js 12 + swcMinify compatibility
  packages/core/src/domain/session/sessionConstants.ts
  packages/core/src/domain/session/sessionManager.spec.ts
  packages/core/src/domain/session/sessionManager.ts
  packages/core/src/domain/session/sessionState.spec.ts
  packages/core/src/domain/session/sessionStore.spec.ts
  packages/core/src/domain/session/sessionStore.ts
  packages/core/src/index.ts
  packages/logs/src/domain/logsSessionManager.ts
  packages/rum-core/src/domain/rumSessionManager.ts
Labels: mergequeue-status: in_progress, staging-22

#3581 🐛 Automatic mock clock cleanup
  packages/core/src/domain/eventRateLimiter/createEventRateLimiter.spec.ts
  packages/core/src/domain/session/sessionManager.spec.ts
  packages/core/src/domain/session/sessionStore.spec.ts
  packages/core/src/domain/session/sessionStoreOperations.spec.ts
  packages/core/src/domain/session/storeStrategies/sessionInCookie.spec.ts
  packages/core/src/tools/instrumentMethod.spec.ts
  packages/core/src/tools/requestIdleCallback.spec.ts
  packages/core/src/tools/taskQueue.spec.ts
  packages/core/src/tools/timer.spec.ts
  packages/core/src/tools/utils/functionUtils.spec.ts
  packages/core/src/tools/valueHistory.spec.ts
  packages/core/src/transport/flushController.spec.ts
  packages/core/src/transport/sendWithRetryStrategy.spec.ts
  packages/core/test/emulate/mockClock.ts
  packages/logs/src/boot/preStartLogs.spec.ts
  packages/logs/src/boot/startLogs.spec.ts
  packages/logs/src/domain/assembly.spec.ts
  packages/logs/src/domain/logger/loggerCollection.spec.ts
  packages/logs/src/domain/logsSessionManager.spec.ts
  packages/rum-core/src/boot/preStartRum.spec.ts
  packages/rum-core/src/boot/rumPublicApi.spec.ts
  packages/rum-core/src/boot/startRum.spec.ts
  packages/rum-core/src/browser/cookieObservable.spec.ts
  packages/rum-core/src/browser/performanceObservable.spec.ts
  packages/rum-core/src/browser/viewportObservable.spec.ts
  packages/rum-core/src/domain/action/clickChain.spec.ts
  packages/rum-core/src/domain/action/computeFrustration.spec.ts
  packages/rum-core/src/domain/action/interactionSelectorCache.spec.ts
  packages/rum-core/src/domain/action/trackClickActions.spec.ts
  packages/rum-core/src/domain/assembly.spec.ts
  packages/rum-core/src/domain/contexts/defaultContext.spec.ts
  packages/rum-core/src/domain/contexts/featureFlagContext.spec.ts
  packages/rum-core/src/domain/contexts/pageStateHistory.spec.ts
  packages/rum-core/src/domain/contexts/urlContexts.spec.ts
  packages/rum-core/src/domain/contexts/viewHistory.spec.ts
  packages/rum-core/src/domain/error/trackConsoleError.spec.ts
  packages/rum-core/src/domain/error/trackReportError.spec.ts
  packages/rum-core/src/domain/rumSessionManager.spec.ts
  packages/rum-core/src/domain/startCustomerDataTelemetry.spec.ts
  packages/rum-core/src/domain/view/trackViews.spec.ts
  packages/rum-core/src/domain/view/viewCollection.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/trackBfcacheMetrics.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/trackInitialViewMetrics.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/trackLoadingTime.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/trackNavigationTimings.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/trackScrollMetrics.spec.ts
  packages/rum-core/src/domain/vital/vitalCollection.spec.ts
  packages/rum-core/src/domain/waitPageActivityEnd.spec.ts
  packages/rum-react/src/domain/performance/reactComponentTracker.spec.tsx
  packages/rum-react/src/domain/performance/timer.spec.ts
  packages/rum/src/domain/deflate/deflateWorker.spec.ts
  packages/rum/src/domain/record/mutationBatch.spec.ts
  packages/rum/src/domain/record/record.spec.ts
  packages/rum/src/domain/record/trackers/trackInput.spec.ts
  packages/rum/src/domain/segmentCollection/segmentCollection.spec.ts
Labels: mergequeue-status: in_progress
