Repository DataDog/browser-sdk, pull requests merged in 2025-03, with the labels that each got.

#3403 🔧 update volta config
  package.json
Labels: mergequeue-status: in_progress

#3404 [RUM-8912] Add documentation to the beforeSend function in configuration
  packages/core/src/domain/configuration/configuration.ts
Labels: mergequeue-status: removed

#3395 ✨ [RUM-7387] Add user id and account id to trace header
  packages/core/src/tools/experimentalFeatures.ts
  packages/logs/src/domain/contexts/commonContext.ts
  packages/logs/src/rawLogsEvent.types.ts
  packages/rum-core/src/boot/rumPublicApi.ts
  packages/rum-core/src/boot/startRum.ts
  packages/rum-core/src/domain/contexts/commonContext.ts
  packages/rum-core/src/domain/requestCollection.ts
  packages/rum-core/src/domain/tracing/encodedContext.spec.ts
  packages/rum-core/src/domain/tracing/encodedContext.ts
  packages/rum-core/src/domain/tracing/tracer.spec.ts
  packages/rum-core/src/domain/tracing/tracer.ts
Labels: staging-10, staging-11

#3392 👷 Bump chrome to 134.0.6998.35-1
  .gitlab-ci.yml
Labels: mergequeue-status: removed

#3399 ⚡️ use `import()` for lazy loading chunks
  webpack.base.js
Labels: staging-10, staging-11

#3420 👷 [RUM-105] use local dev server for local e2e tests
  test/e2e/lib/framework/createTest.ts
  test/e2e/lib/framework/index.ts
  test/e2e/lib/framework/sdkBuilds.ts
  test/e2e/lib/framework/serverApps/mock.ts
  test/e2e/lib/helpers/playwright.ts
  test/e2e/playwright.base.config.ts
  test/e2e/scenario/recorder/recorder.scenario.ts
  test/e2e/scenario/recorder/shadowDom.scenario.ts
  test/e2e/scenario/recorder/viewports.scenario.ts
  test/e2e/scenario/rum/resources.scenario.ts
  test/e2e/scenario/rum/s8sInject.scenario.ts
  test/e2e/scenario/rum/sessions.scenario.ts
  test/e2e/scenario/telemetry.scenario.ts
  test/e2e/tsconfig.json
Labels: staging-12

#3417 ♻️ [RUM-8795] Replace XHR with Fetch for HTTP requests
  packages/core/src/domain/configuration/endpointBuilder.spec.ts
  packages/core/src/domain/configuration/endpointBuilder.ts
  packages/core/src/domain/configuration/transportConfiguration.spec.ts
  packages/core/src/transport/httpRequest.spec.ts
  packages/core/src/transport/httpRequest.ts
  packages/core/test/interceptRequests.ts
  packages/logs/src/boot/startLogs.spec.ts
  packages/rum-core/src/domain/requestCollection.spec.ts
Labels: staging-11

#3406 🐛 [RUM-99] don't stop RUM/Replay on beforeunload
  packages/core/src/browser/pageMayExitObservable.spec.ts
  packages/core/src/browser/pageMayExitObservable.ts
  packages/core/src/index.ts
  packages/core/src/transport/batch.ts
  packages/core/src/transport/flushController.spec.ts
  packages/core/src/transport/flushController.ts
  packages/core/src/transport/startBatchWithReplica.spec.ts
  packages/core/src/transport/startBatchWithReplica.ts
  packages/logs/src/boot/startLogs.ts
  packages/logs/src/domain/logsTelemetry.ts
  packages/logs/src/transport/startLogsBatch.ts
  packages/rum-core/src/boot/startRum.ts
  packages/rum-core/src/domain/action/trackClickActions.ts
  packages/rum-core/src/domain/lifeCycle.ts
  packages/rum-core/src/domain/view/trackViews.spec.ts
  packages/rum-core/src/domain/view/trackViews.ts
  packages/rum-core/src/transport/startRumBatch.ts
  packages/rum/src/boot/postStartStrategy.ts
  packages/rum/src/boot/recorderApi.spec.ts
  packages/rum/src/boot/startRecording.spec.ts
  packages/rum/src/domain/segmentCollection/segmentCollection.spec.ts
  packages/rum/src/domain/segmentCollection/segmentCollection.ts
  test/e2e/scenario/rum/sessions.scenario.ts
Labels: staging-12

#3446 👌 [RUM-99] don't set views as inactive when the page is exiting
  packages/rum-core/src/domain/view/trackViews.spec.ts
  packages/rum-core/src/domain/view/trackViews.ts
Labels: staging-13
