Repository DataDog/browser-sdk, pull requests merged in 2025-06, with the labels that each got.

#3573 🐛 [RUM-10002] Verify the document was not hidden while loading
  packages/rum-core/src/domain/view/trackViews.ts
  packages/rum-core/src/domain/view/viewMetrics/trackFirstContentfulPaint.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/trackFirstHidden.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/trackFirstHidden.ts
  packages/rum-core/src/domain/view/viewMetrics/trackFirstInput.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/trackInitialViewMetrics.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/trackInitialViewMetrics.ts
  packages/rum-core/src/domain/view/viewMetrics/trackLargestContentfulPaint.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/trackLoadingTime.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/trackLoadingTime.ts
Labels: mergequeue-status: in_progress, staging-22, staging-23

#3585 ⚗ Interim integration instructions/script for unpublished flagging npm package.
  packages/flagging/INTEGRATE-FLAGGING-PACKAGE.sh
  packages/flagging/package.json
  packages/flagging/src/hello.ts
  yarn.lock
Labels: mergequeue-status: done

#3603 FFL-158: fix flagging api path
  packages/flagging/INTEGRATE-FLAGGING-PACKAGE.sh
  packages/flagging/src/openfeature/provider.ts
Labels: mergequeue-status: in_progress

#3609 👌 [RUM-10290] Remove built extensions from ignored in eslint.config
  eslint.config.mjs
  scripts/extensions/build-testing-extensions.js
  test/apps/base-extension/manifest.json
  test/apps/base-extension/package.json
  test/apps/base-extension/src/background.ts
  test/apps/base-extension/src/contentScript.ts
  test/apps/base-extension/tsconfig.json
  test/apps/base-extension/webpack.config.js
  test/apps/base-extension/yarn.lock
  test/apps/react/yarn.lock
  test/apps/vanilla/yarn.lock
Labels: staging-24

#3631 Update changelog-to-confluence: Update secret names, name of page being published
  .github/workflows/changelog-to-confluence.yml
Labels: mergequeue-status: in_progress

#3628 ♻️ [RUM-10074] Use createTest in developer extensions tests
  test/e2e/scenario/developer-extension/developerExtension.scenario.ts
Labels: staging-25

#3629 [IR-39238] Add session diagnostic telemetry and improve configuration timing
  packages/core/src/domain/configuration/configuration.ts
  packages/core/src/domain/configuration/endpointBuilder.ts
  packages/core/src/domain/configuration/index.ts
  packages/core/src/domain/configuration/transportConfiguration.spec.ts
  packages/core/src/domain/configuration/transportConfiguration.ts
  packages/core/src/domain/intakeSites.ts
  packages/core/src/domain/session/sessionManager.ts
  packages/core/src/domain/session/sessionStore.ts
  packages/core/src/domain/session/sessionStoreOperations.ts
  packages/core/src/domain/session/storeStrategies/sessionInCookie.ts
  packages/core/src/domain/synthetics/syntheticsWorkerValues.ts
  packages/core/src/domain/telemetry/telemetry.spec.ts
  packages/core/src/domain/telemetry/telemetry.ts
  packages/core/src/index.ts
  packages/logs/src/boot/preStartLogs.ts
  packages/rum-core/src/boot/preStartRum.ts
  packages/rum-core/src/boot/startRum.ts
  packages/rum-core/src/domain/contexts/syntheticsContext.ts
Labels: staging-25, staging-24

#3637 🐛 [RUM-10366] mitigate cookie dead lock
  packages/core/src/domain/session/sessionStoreOperations.spec.ts
  packages/core/src/domain/session/sessionStoreOperations.ts
  packages/core/test/emulate/mockStorages.ts
  packages/core/test/index.ts
Labels: staging-25

#3647 🔊 [IR-39238] add cookie data in debug logs
  packages/core/src/domain/session/sessionManager.ts
Labels: staging-25

#3654 🍒 [RUM-10101] Persist session cookie to one year when opt-in anonymous user tracking (#3559)
  packages/core/src/domain/session/storeStrategies/sessionInCookie.spec.ts
  packages/core/src/domain/session/storeStrategies/sessionInCookie.ts
Labels: staging-26

#3660 feat: Allow custom headers
  packages/flagging/.gitignore
  packages/flagging/src/openfeature/provider.spec.ts
  packages/flagging/src/openfeature/provider.ts
Labels: mergequeue-status: rejected
