Repository DataDog/browser-sdk, pull requests merged in 2025-04, with the labels that each got.

#3393 ⚡️ Remove customer data track for perf and bundle size
  packages/core/src/domain/context/contextManager.spec.ts
  packages/core/src/domain/context/contextManager.ts
  packages/core/src/domain/context/customerDataTracker.spec.ts
  packages/core/src/domain/context/customerDataTracker.ts
  packages/core/src/domain/context/storeContextManager.spec.ts
  packages/core/src/index.ts
  packages/logs/src/boot/logsPublicApi.ts
  packages/logs/src/boot/startLogs.spec.ts
  packages/logs/src/domain/assembly.spec.ts
  packages/logs/src/domain/logger.spec.ts
  packages/logs/src/domain/logger.ts
  packages/logs/src/domain/logger/loggerCollection.spec.ts
  packages/rum-core/src/boot/preStartRum.ts
  packages/rum-core/src/boot/rumPublicApi.spec.ts
  packages/rum-core/src/boot/rumPublicApi.ts
  packages/rum-core/src/boot/startRum.spec.ts
  packages/rum-core/src/boot/startRum.ts
  packages/rum-core/src/domain/contexts/accountContext.spec.ts
  packages/rum-core/src/domain/contexts/accountContext.ts
  packages/rum-core/src/domain/contexts/featureFlagContext.spec.ts
  packages/rum-core/src/domain/contexts/featureFlagContext.ts
  packages/rum-core/src/domain/contexts/globalContext.spec.ts
  packages/rum-core/src/domain/contexts/globalContext.ts
  packages/rum-core/src/domain/contexts/userContext.spec.ts
  packages/rum-core/src/domain/contexts/userContext.ts
  packages/rum-core/src/domain/startCustomerDataTelemetry.spec.ts
  packages/rum-core/src/domain/startCustomerDataTelemetry.ts
  packages/rum-core/test/mockContexts.ts
Labels: staging-14

#3450 [RUM Profiler] Improvements around Views and Long Tasks
  packages/rum/src/boot/profilerApi.ts
  packages/rum/src/domain/profiling/profiler.spec.ts
  packages/rum/src/domain/profiling/profiler.ts
  packages/rum/src/domain/profiling/transport/transport.ts
  packages/rum/src/domain/profiling/types/rumProfiler.types.ts
  packages/rum/src/domain/profiling/utils/longTaskRegistry.ts
Labels: staging-13, staging-14

#3459 [RUM Profiler] Fix collection of profiles after visibility change
  packages/rum/src/domain/profiling/profiler.spec.ts
  packages/rum/src/domain/profiling/profiler.ts
  packages/rum/src/domain/profiling/types/rumProfiler.types.ts
Labels: staging-14

#3445 use baggage for user.id / account.id forwarding
  packages/rum-core/src/domain/configuration/configuration.spec.ts
  packages/rum-core/src/domain/configuration/configuration.ts
  packages/rum-core/src/domain/tracing/tracer.spec.ts
  packages/rum-core/src/domain/tracing/tracer.ts
Labels: staging-14

#3475 🐛 Improve context properties sanitization
  packages/core/src/domain/context/contextManager.spec.ts
  packages/core/src/domain/context/contextManager.ts
  packages/logs/src/boot/logsPublicApi.spec.ts
  packages/rum-core/src/boot/rumPublicApi.spec.ts
  packages/rum-core/src/domain/contexts/accountContext.spec.ts
  packages/rum-core/src/domain/contexts/userContext.spec.ts
Labels: staging-16

#3430 ⚗️ ✨ [RUM-8365] Propagate session id in `baggage` header
  packages/rum-core/src/domain/tracing/tracer.spec.ts
  packages/rum-core/src/domain/tracing/tracer.ts
Labels: staging-16, mergequeue-status: done

#3493 ♻️ Decouple the display context from assembly using hooks
  packages/rum-core/src/boot/startRum.ts
  packages/rum-core/src/domain/assembly.spec.ts
  packages/rum-core/src/domain/assembly.ts
  packages/rum-core/src/domain/contexts/displayContext.spec.ts
  packages/rum-core/src/domain/contexts/displayContext.ts
  packages/rum-core/test/mockContexts.ts
Labels: staging-16

#3494 ♻️ Decouple the connectivity context from assembly using hooks
  packages/rum-core/src/boot/startRum.ts
  packages/rum-core/src/domain/assembly.spec.ts
  packages/rum-core/src/domain/assembly.ts
  packages/rum-core/src/domain/contexts/connectivityContext.spec.ts
  packages/rum-core/src/domain/contexts/connectivityContext.ts
Labels: staging-17

#3488 ✨ Add publicPath configuration to webpack setups
  packages/logs/webpack.config.js
  packages/rum-slim/webpack.config.js
  packages/rum/webpack.config.js
  packages/worker/webpack.config.js
  scripts/dev-server.js
  webpack.base.js
Labels: mergequeue-status: in_progress

#3480 ♻️trackCumulativeLayoutShift: Sort sources in attribution data before picking the 1st one
  packages/rum-core/src/domain/view/viewMetrics/getClsAttributionImpactedArea.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/getClsAttributionImpactedArea.ts
  packages/rum-core/src/domain/view/viewMetrics/trackCumulativeLayoutShift.ts
Labels: staging-16

#3489 ♻️ [RUM-9549] Decouple the session context from assembly using hooks
  packages/rum-core/src/boot/startRum.spec.ts
  packages/rum-core/src/boot/startRum.ts
  packages/rum-core/src/domain/assembly.spec.ts
  packages/rum-core/src/domain/assembly.ts
  packages/rum-core/src/domain/contexts/sessionContext.spec.ts
  packages/rum-core/src/domain/contexts/sessionContext.ts
  packages/rum-core/src/domain/contexts/urlContexts.spec.ts
  packages/rum-core/src/domain/contexts/urlContexts.ts
  packages/rum-core/src/domain/contexts/viewHistory.ts
  packages/rum-core/src/domain/view/trackViews.ts
  packages/rum-core/src/domain/view/viewCollection.spec.ts
  packages/rum-core/src/domain/view/viewCollection.ts
  packages/rum-core/src/domain/view/viewMetrics/trackFirstHidden.spec.ts
  packages/rum-core/src/hooks.spec.ts
  packages/rum-core/src/hooks.ts
  packages/rum-core/src/rawRumEvent.types.ts
Labels: staging-17, staging-18

#3499 ♻️ [RUM-9667] refactor stack trace computation
  packages/core/src/domain/console/consoleObservable.ts
  packages/core/src/domain/error/error.spec.ts
  packages/core/src/domain/error/error.ts
  packages/core/src/domain/error/trackRuntimeError.spec.ts
  packages/core/src/domain/error/trackRuntimeError.ts
  packages/core/src/tools/stackTrace/computeStackTrace.ts
  packages/logs/src/domain/console/consoleCollection.spec.ts
  packages/logs/src/domain/logger.ts
  packages/rum-core/src/domain/error/errorCollection.ts
  packages/rum-core/src/domain/error/trackConsoleError.spec.ts
Labels: staging-17, mergequeue-status: in_progress
