Repository DataDog/browser-sdk, pull requests merged in 2025-02, with the labels that each got.

#3313 🔊 Revert hooks and add missing URL context telemetry
  packages/core/src/tools/experimentalFeatures.ts
  packages/core/src/tools/valueHistory.ts
  packages/rum-core/src/boot/startRum.spec.ts
  packages/rum-core/src/boot/startRum.ts
  packages/rum-core/src/domain/assembly.spec.ts
  packages/rum-core/src/domain/assembly.ts
  packages/rum-core/src/domain/contexts/internalContext.spec.ts
  packages/rum-core/src/domain/contexts/urlContexts.spec.ts
  packages/rum-core/src/domain/contexts/urlContexts.ts
  packages/rum-core/src/domain/contexts/viewHistory.ts
  packages/rum-core/src/domain/view/setupViewTest.specHelper.ts
  packages/rum-core/src/domain/view/trackViews.spec.ts
  packages/rum-core/src/domain/view/trackViews.ts
  packages/rum-core/src/domain/view/viewCollection.spec.ts
  packages/rum-core/src/domain/view/viewCollection.ts
  packages/rum-core/src/hooks.spec.ts
  packages/rum-core/src/hooks.ts
  packages/rum-core/src/rawRumEvent.types.ts
  packages/rum-core/test/formatValidation.ts
  packages/rum-core/test/mockContexts.ts
Labels: staging-06

#3323 🐛 Fix missing URL context
  packages/core/src/tools/valueHistory.spec.ts
  packages/core/src/tools/valueHistory.ts
Labels: staging-06

#3306 👷‍♀️ [RUM-8295] Change anonymous id format to uuid
  packages/core/src/domain/session/sessionState.ts
  packages/core/src/domain/session/storeStrategies/sessionInCookie.spec.ts
  packages/core/src/domain/session/storeStrategies/sessionInLocalStorage.spec.ts
  packages/core/src/domain/user/user.spec.ts
  packages/core/src/domain/user/user.ts
  packages/core/src/index.ts
  test/e2e/lib/helpers/session.ts
  test/e2e/scenario/rum/sessions.scenario.ts
Labels: staging-05

#3305 ♻️ [RUM-8319] Use assembly hook for action
  packages/rum-core/src/boot/startRum.ts
  packages/rum-core/src/domain/action/actionCollection.spec.ts
  packages/rum-core/src/domain/action/actionCollection.ts
  packages/rum-core/src/domain/assembly.spec.ts
  packages/rum-core/src/domain/assembly.ts
Labels: staging-07

#3310 ♻️ [RUM-8340] Use assembly hook for ci and synthetics contexts
  packages/rum-core/src/boot/startRum.ts
  packages/rum-core/src/domain/assembly.spec.ts
  packages/rum-core/src/domain/assembly.ts
  packages/rum-core/src/domain/contexts/ciVisibilityContext.spec.ts
  packages/rum-core/src/domain/contexts/ciVisibilityContext.ts
  packages/rum-core/src/domain/contexts/syntheticsContext.spec.ts
  packages/rum-core/src/domain/contexts/syntheticsContext.ts
  packages/rum-core/src/domain/rumSessionManager.ts
Labels: staging-07, staging-08

#3336 🔥 remove some workarounds related to unsupported browsers
  packages/rum-core/src/domain/getSelectorFromElement.spec.ts
  packages/rum-core/src/domain/getSelectorFromElement.ts
Labels: staging-07

#3320 ✨ [RUM-7459] Collect error context from a custom Error field
  packages/core/src/domain/console/consoleObservable.spec.ts
  packages/core/src/domain/console/consoleObservable.ts
  packages/core/src/domain/error/error.spec.ts
  packages/core/src/domain/error/error.ts
  packages/core/src/domain/error/error.types.ts
  packages/logs/src/domain/console/consoleCollection.spec.ts
  packages/logs/src/domain/console/consoleCollection.ts
  packages/logs/src/domain/createErrorFieldFromRawError.spec.ts
  packages/logs/src/domain/logger.spec.ts
  packages/logs/src/domain/runtimeError/runtimeErrorCollection.spec.ts
  packages/logs/src/domain/runtimeError/runtimeErrorCollection.ts
  packages/rum-core/src/domain/error/errorCollection.spec.ts
  packages/rum-core/src/domain/error/errorCollection.ts
  packages/rum-core/src/domain/error/trackConsoleError.spec.ts
Labels: staging-08

#3359 Define an error type and message for handling stacks
  packages/core/src/domain/console/consoleObservable.spec.ts
  packages/core/src/domain/console/consoleObservable.ts
  packages/core/src/tools/instrumentMethod.spec.ts
  packages/core/src/tools/instrumentMethod.ts
  packages/core/src/tools/stackTrace/handlingStack.spec.ts
  packages/core/src/tools/stackTrace/handlingStack.ts
  packages/logs/src/domain/logger.ts
  packages/rum-core/src/boot/rumPublicApi.spec.ts
  packages/rum-core/src/boot/rumPublicApi.ts
  packages/rum-react/src/domain/error/addReactError.ts
  test/e2e/scenario/microfrontend.scenario.ts
  test/e2e/scenario/rum/errors.scenario.ts
Labels: mergequeue-status: rejected

#3378 🐛 Fix empty string for resource url in LCP
  packages/rum-core/src/domain/view/viewMetrics/trackLargestContentfulPaint.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/trackLargestContentfulPaint.ts
Labels: staging-09
