Repository DataDog/browser-sdk, pull requests merged in 2025-09, with the labels that each got.

#3807 🐛 [PANA-3960] Allow more queued request data for better session replay reliability
  packages/core/src/transport/sendWithRetryStrategy.spec.ts
  packages/core/src/transport/sendWithRetryStrategy.ts
Labels: staging-35

#3779 🔊 [RUM-11233] collect remote configuration metrics
  packages/core/src/domain/telemetry/index.ts
  packages/core/src/domain/telemetry/telemetry.spec.ts
  packages/core/src/domain/telemetry/telemetry.ts
  packages/core/src/index.ts
  packages/rum-core/src/boot/startRum.ts
  packages/rum-core/src/domain/configuration/configuration.ts
  packages/rum-core/src/domain/configuration/remoteConfiguration.spec.ts
  packages/rum-core/src/domain/configuration/remoteConfiguration.ts
  packages/rum-core/src/domain/startCustomerDataTelemetry.spec.ts
  packages/rum-core/src/domain/startCustomerDataTelemetry.ts
  packages/rum-core/src/domain/view/viewMetrics/startInitialViewMetricsTelemetry.spec.ts
  packages/rum-core/src/domain/view/viewMetrics/startInitialViewMetricsTelemetry.ts
  packages/rum/src/boot/lazyLoadRecorder.spec.ts
  packages/rum/src/boot/postStartStrategy.ts
  packages/rum/src/boot/recorderApi.spec.ts
  packages/rum/src/boot/startRecording.spec.ts
  packages/rum/src/boot/startRecording.ts
  packages/rum/src/domain/segmentCollection/startSegmentTelemetry.spec.ts
  packages/rum/src/domain/segmentCollection/startSegmentTelemetry.ts
  packages/rum/src/domain/startRecorderInitTelemetry.spec.ts
  packages/rum/src/domain/startRecorderInitTelemetry.ts
Labels: staging-38

#3862 👷 [mob-session] make `test-performances` more resilient
  scripts/lib/computeBundleSize.ts
  scripts/lib/executionUtils.ts
  scripts/lib/gitUtils.ts
  scripts/performance/index.ts
  scripts/performance/lib/bundleSizes.ts
  scripts/performance/lib/constants.ts
  scripts/performance/lib/cpuPerformance.ts
  scripts/performance/lib/fetchPerformanceMetrics.ts
  scripts/performance/lib/memoryPerformance.ts
  scripts/performance/lib/reportAsAPrComment.spec.ts
  scripts/performance/lib/reportAsAPrComment.ts
  scripts/performance/lib/reportToDatadog.ts
  scripts/show-bundle-size.ts
Labels: mergequeue-status: in_progress
